seek-oss/skuba

- src/cli/build.ts
- src/cli/configure/index.ts
- src/cli/format.ts
- src/cli/help.ts
- src/cli/init/index.ts
- src/cli/lint.ts
- src/cli/start/index.ts
- src/cli/test.ts
- src/cli/version.ts
- src/skuba.ts
This seems a lot more like regular code, and will be more testable.
They are still imported dynamically as I don't like the idea of loading all command modules every time the CLI is invoked.
> Export CLI commands as functions

- .changeset/sweet-coats-develop.md
- README.md
- docs/migrating-from-seek-module-toolkit.md
- src/cli/buildPackage.ts
- src/utils/command.ts
This builds on the proposal in #11 with a separate command for migration from `smt build`.
> Add build-package command

- .changeset/sweet-coats-develop.md
I'm curious how Changesets will handle this.
> Mark #15 as a minor change

- .changeset/smooth-goats-kick.md
- .eslintrc.js
- src/cli/configure/analysis/git.ts
- src/cli/configure/analysis/package.ts
- src/cli/configure/applyConfiguration.ts
- src/cli/configure/ensureTemplateCompletion.ts
- src/cli/configure/index.ts
- src/cli/format.ts
- src/cli/init/getConfig.ts
- src/cli/init/git.ts
- src/cli/init/index.ts
- src/cli/start/http.ts
- src/cli/version.ts
- src/skuba.ts
- src/utils/copy.ts
- src/utils/error.ts
- src/utils/exec.ts
- src/utils/help.ts
- src/utils/logging.ts
- src/utils/logo.ts
This defines a common set of logging functions that try to communicate more intent than plain old `console.log` and `console.error`.
> Unify logging

- docs/migrating-from-seek-module-toolkit.md
- docs/migrating-from-seek-skuba.md
- Document proposed `@seek/skuba` migration
- Add TL;DR for `seek-module-toolkit` migration
> Extend migration docs

- .changeset/lazy-rings-double.md
- scripts/test-template.sh
- template/koa-rest-api/src/config.ts
Resolves #64. This is now validated in CI.
> Ensure `koa-rest-api` passes lint on init

- .changeset/rich-lemons-crash.md
- .dockerignore
- .eslintignore
- .gitignore
- .prettierignore
- src/cli/configure/analysis/__snapshots__/project.test.ts.snap
- template/base/_.gitignore
These are created by `npm pack`.
> Ignore .tgz files

- .changeset/empty-boats-cross.md
- src/cli/configure/processing/__snapshots__/ignoreFile.test.ts.snap
- src/cli/configure/processing/ignoreFile.test.ts
- src/cli/configure/processing/ignoreFile.ts
Configure was adding a newline on each run.
> Tame newlines in ignore files

- .changeset/neat-pigs-exist.md
- template/lambda-sqs-worker/package.json
- template/lambda-sqs-worker/src/framework/validation.test.ts
> Snapshot improved Runtypes error messaging

- template/oss-npm-package/README.md
- template/private-npm-package/README.md
As discussed with @jahredhope.
> Link out to package release processes

- .changeset/lemon-pugs-grow.md
- src/cli/configure/processing/package.test.ts
- src/cli/configure/processing/package.ts
> Sort `package.json#/skuba` fields

- src/cli/configure/processing/package.test.ts
- src/cli/configure/processing/package.ts
I'm not in the mood to sort `preprepreprebuild`s.
> Do not sort `package.json#/scripts`

- .changeset/eight-brooms-jog.md
- src/cli/configure/modules/jest.ts
Not sure why I was mean and excluded this before.
> Bless `collectCoverageFrom` Jest option

- docs/migrating-from-seek-skuba.md
> Bump documented `@seek/skuba` version

- .changeset/silver-planets-repeat.md
- jest-preset.js
> Collect coverage from TSX files

- README.md
- docs/babel.md
- docs/migrating-from-seek-module-toolkit.md
- docs/migrating-from-seek-skuba.md
- Mention package development upfront
- Use fewer backticks
- Hyperlink Slack channels
> Tweak doco

- CONTRIBUTING.md
Really weak copy+paste game this week.
> Fix CONTRIBUTING.md links

- yarn.lock
https://app.snyk.io/vuln/SNYK-JS-LODASH-567746
> Lock in lodash 4.17.19

- yarn.lock
https://snyk.io/vuln/SNYK-JS-LODASH-590103
> Relock Lodash for security

- yarn.lock
- https://app.snyk.io/vuln/npm:mem:20180117
- https://app.snyk.io/vuln/SNYK-JS-YARGSPARSER-560381
> Relock deps for security

- CHANGELOG.md
I updated the release manually and forgot about this.
> Include more details in TypeScript 4.0 changelog

- .changeset/sharp-books-cross.md
- src/cli/configure/modules/jest.ts
- src/cli/configure/processing/typescript.test.ts
- src/cli/configure/processing/typescript.ts
https://devblogs.microsoft.com/typescript/announcing-typescript-4-0/#usage-of-typescripts-node-factory-is-deprecated
> Switch to TypeScript 4.0 node factory API

- .changeset/lemon-bananas-flash.md
- src/cli/configure/dependencies/skubaDeps.ts
> Configure eslint-config-skuba + semantic-release

- .changeset/khaki-pants-sparkle.md
- src/cli/build/tsc.ts
This is a small step towards better monorepo support.
https://www.typescriptlang.org/docs/handbook/project-references.html
> Support `tsc --build` flag

- .changeset/kind-bats-brake.md
- README.md
- template/koa-rest-api/package.json
- template/koa-rest-api/src/framework/logging.ts
- template/lambda-sqs-worker/package.json
- template/lambda-sqs-worker/src/framework/handler.ts
- template/lambda-sqs-worker/src/framework/logging.ts
https://github.com/seek-oss/logger
> Adopt `@seek/logger`

- .changeset/five-lies-mix.md
- package.json
- yarn.lock
See https://github.com/whitecolor/ts-node-dev/issues/224
> Pin ts-node-dev 1.0.0-pre.63

- .changeset/three-lizards-bake.md
- template/express-rest-api/docker-compose.yml
- template/greeter/docker-compose.yml
- template/koa-rest-api/docker-compose.yml
- template/lambda-sqs-worker/docker-compose.yml
This is required for #222 to make any sense.
> Mount working directory in Docker Compose

- .changeset/early-rabbits-wait.md
The next release is fairly unexciting so would work better as a patch.
> Mark `.me` additions as a patch

- .changeset/green-needles-wait.md
- jest-preset.js
- src/cli/lint.ts
- template/koa-rest-api/src/framework/server.test.ts
Per https://eslint.org/docs/user-guide/command-line-interface#-report-unused-disable-directives
> Check for unused ESLint disable directives

- src/api/net/socket.ts
I didn't read the TS 4.1 release notes closely.
> Use void Promise constructor

- yarn.lock
https://app.snyk.io/vuln/SNYK-JS-Y18N-1021887
> Relock for y18n

- .changeset/clean-cats-dream.md
- template/koa-rest-api/src/api/healthCheck.ts
- template/koa-rest-api/src/api/jobs/getJobs.ts
- template/koa-rest-api/src/api/jobs/postJob.ts
- template/koa-rest-api/src/api/smokeTest.ts
- template/koa-rest-api/src/framework/logging.ts
- template/koa-rest-api/src/framework/server.test.ts
- template/koa-rest-api/src/framework/server.ts
- template/koa-rest-api/src/framework/validation.ts
- template/koa-rest-api/src/testing/server.ts
- template/koa-rest-api/src/types/koa.ts
> Use typed Koa context

- .changeset/thick-dancers-taste.md
- README.md
- package.json
- src/cli/configure/index.ts
- src/cli/help.ts
- src/cli/init/index.ts
- src/skuba.ts
- src/utils/logo.ts
- src/utils/version.ts
- yarn.lock
Closes #109.
|offline|up to date|out of date
|:-:|:-:|:-:
> Check for newer skuba versions

- package.json
- src/cli/node.ts
- src/cli/start.ts
- src/utils/validation.ts
- src/wrapper/functionHandler.ts
- src/wrapper/http.ts
- src/wrapper/index.ts
- src/wrapper/main.test.ts
- src/wrapper/main.ts
- src/wrapper/requestListener.ts
- src/wrapper/testing/asyncFunctionHandler.ts
- src/wrapper/testing/expressRequestListener.ts
- src/wrapper/testing/invalidRequestListener.ts
- src/wrapper/testing/koaRequestListener.ts
- src/wrapper/testing/miscellaneousExportModule.ts
- src/wrapper/testing/noExportModule.ts
- src/wrapper/testing/syncFunctionHandler.ts
- yarn.lock
The wrapper has gotten a little bit involved and now caters for several different entry point configurations. This tests its main logic with a set of happy and sad entry points.
> Test node/start wrapper

- src/cli/configure/modules/jest.test.ts
- src/cli/configure/processing/typescript.ts
This has always annoyed me greatly.
> Add blank line after `jest.config.ts` imports

- .changeset/eleven-phones-reflect.md
- template/express-rest-api/.buildkite/pipeline.yml
- template/koa-rest-api/.buildkite/pipeline.yml
- template/lambda-sqs-worker/.buildkite/pipeline.yml
https://buildkite.com/docs/pipelines/command-step#manual-retry-attributes
> Enable retry of successful deployment steps

- .changeset/beige-tips-laugh.md
- .changeset/light-files-nail.md
- template/lambda-sqs-worker/.buildkite/pipeline.yml
This runs the dev deployment concurrently with test + lint on the default branch. Merged PRs should have already passed test + lint on their original branches, and the dev environment shouldn't be precious. Plus, broken deployments will be more easily detected and rolled back once we recommend a smoke test pattern.
> Simplify Lambda Buildkite pipeline

- .changeset/gorgeous-dancers-buy.md
- .changeset/pink-bikes-roll.md
- template/express-rest-api/gantry.apply.yml
- template/express-rest-api/src/api/healthCheck.ts
- template/express-rest-api/src/api/smokeTest.ts
- template/express-rest-api/src/app.test.ts
- template/express-rest-api/src/app.ts
- template/express-rest-api/src/listen.ts
- template/express-rest-api/src/register.ts
- template/koa-rest-api/gantry.apply.yml
- template/koa-rest-api/src/api/smokeTest.ts
- template/koa-rest-api/src/app.ts
- template/koa-rest-api/src/listen.ts
- template/koa-rest-api/src/register.ts
- template/koa-rest-api/src/storage/jobs.ts
> Clarify API health checks and smoke tests

- .changeset/young-terms-sleep.md
- README.md
- template/express-rest-api/README.md
- template/greeter/README.md
- template/koa-rest-api/README.md
- template/lambda-sqs-worker/README.md
- template/oss-npm-package/README.md
- template/private-npm-package/README.md
> Uplift template READMEs

- .changeset/fair-hairs-protect.md
- src/cli/node.ts
- src/cli/start.ts
> Fix module alias registration

- yarn.lock
- https://app.snyk.io/vuln/SNYK-JS-LODASH-1040724
- https://app.snyk.io/vuln/SNYK-JS-HANDLEBARS-1056767
- https://app.snyk.io/vuln/SNYK-JS-LODASH-1018905
> Relock for security

- .changeset/silly-knives-prove.md
> Delete changeset for #356

- .changeset/wise-papayas-add.md
- template/express-rest-api/.buildkite/pipeline.yml
- template/express-rest-api/gantry.apply.yml
- template/koa-rest-api/.buildkite/pipeline.yml
- template/koa-rest-api/gantry.apply.yml
The next version of the Gantry plugin will start requiring this option.
> Move Gantry region config to plugin options

- README.md
- Note that `@seek/logger` is no longer private
- Remove `@seek/node-authentication` as it is no longer directional
> Refresh package list

- yarn.lock
https://app.snyk.io/vuln/SNYK-JS-GLOBPARENT-1016905
> Relock for glob-parent

- .changeset/polite-bobcats-accept.md
- src/cli/init/index.ts
> Mention GitHub repo creation on init

- rich-books-confess.md
- tasty-chairs-camp.md
Not sure how these ended up in the repo root 😕.
> Remove stranded changesets

- yarn.lock
https://snyk.io/vuln/SNYK-JS-NODENOTIFIER-1035794
> Relock node-notifier

- yarn.lock
https://app.snyk.io/vuln/SNYK-JS-HOSTEDGITINFO-1088355
> Relock hosted-git-info

- .changeset/silent-suits-mate.md
- template/express-rest-api/Dockerfile
- template/greeter/Dockerfile
- template/koa-rest-api/Dockerfile
- template/lambda-sqs-worker-cdk/Dockerfile
- template/lambda-sqs-worker/Dockerfile
This was raised by @jahredhope and @brian-captain-crosby in Slack. Thanks!
> Prune `devDependencies` in Dockerfiles

- .github/renovate.json5
- Migrate config to newest syntax
- Make `devDependencies` a fortnightly thing
- Enable lock file maintenance
> Uplift Renovate config

- .changeset/beige-paws-report.md
- src/cli/lint.test.ts
This is housekeeping for #445.
> Mark up Prettier 2.3.1 changes

- .changeset/afraid-humans-design.md
- .changeset/new-falcons-raise.md
- .changeset/quiet-actors-live.md
- .changeset/wicked-dodos-occur.md
- template/express-rest-api/.buildkite/pipeline.yml
- template/express-rest-api/Dockerfile
- template/express-rest-api/Dockerfile.dev-deps
- template/express-rest-api/gantry.build.yml
- template/express-rest-api/package.json
- template/koa-rest-api/.buildkite/pipeline.yml
- template/koa-rest-api/Dockerfile
- template/koa-rest-api/Dockerfile.dev-deps
- template/koa-rest-api/gantry.build.yml
- template/koa-rest-api/package.json
This is now well-supported by the v5 Buildkite stack and https://github.com/seek-oss/docker-ecr-cache-buildkite-plugin.
> Use Docker Build secrets in API templates

- .changeset/new-needles-design.md
- template/express-rest-api/package.json
- template/express-rest-api/src/app.ts
- template/express-rest-api/src/config.ts
- template/express-rest-api/src/listen.ts
- template/koa-rest-api/package.json
- template/koa-rest-api/src/app.test.ts
- template/koa-rest-api/src/app.ts
- template/koa-rest-api/src/config.ts
- template/koa-rest-api/src/listen.ts
> Reduce app boilerplate in API templates

- package.json
- yarn.lock
Resolves https://app.snyk.io/vuln/SNYK-JS-TRIMOFFNEWLINES-1296850.
> Drop transitive trim-off-newlines dependency

- CHANGELOG.md
- docs/about.md
- scripts/deploy.sh
- site/_config.yml
I'm curious if Changesets is going to clobber my changes here; we should be able to see once the Version Packages PR rebases on top of this.
> Include changelog on doc site

- docs/cli/lint.md
- docs/deep-dives/eslint.md
This incorporates some content from our internal Skutorial, as we discussed that we should place content closer to the actual tools at play.
> Extend lint docs

- .changeset/config.json
- package.json
- yarn.lock
This should be able to tag changes with their PR #. I'm not sure how this will work with the existing changelog entries but we'll have to wait and see.
> Try GitHub Changesets changelog format

- src/cli/configure/index.ts
- src/cli/init/index.ts
- src/skuba.ts
- src/utils/error.ts
`process.exit` is rather annoying to work with in tests.
> Reduce `process.exit`ing

- docs/cli/lint.md
> Remove embarrassing directory reveal

- .github/workflows/validate.yml
pull_request: https://github.com/seek-oss/skuba/pull/571/checks?check_run_id=3710322587
push: https://github.com/seek-oss/skuba/pull/571/checks?check_run_id=3710309383
> Try to fix validate workflow conditional

- docs/cli/configure.md
- docs/cli/init.md
- docs/cli/run.md
This brings across a bunch of remaining content from the Skutorial. I think this is sufficient to free me from my Tech Onboarding guilt; the remaining Skutorial content is fairly specific to particular templates and internal workings, and may be ported to separate deep dive topics in future.
> Expand initial CLI docs

- .changeset/fair-tables-notice.md
- src/cli/configure/modules/tsconfig.test.ts
- src/cli/configure/modules/tsconfig.ts
> Tone down Dockerfile `outDir` processing

- .changeset/loud-apricots-leave.md
- .gitignore
- src/cli/__snapshots__/format.int.test.ts.snap
- src/cli/__snapshots__/lint.int.test.ts.snap
- src/cli/adapter/eslint.ts
- src/cli/configure/analysis/__snapshots__/project.test.ts.snap
- template/base/_.gitignore
> Enable ESLint caching

- .changeset/twenty-avocados-poke.md
- template/express-rest-api/docker-compose.yml
- template/greeter/docker-compose.yml
- template/koa-rest-api/docker-compose.yml
- template/lambda-sqs-worker-cdk/docker-compose.yml
- template/lambda-sqs-worker/docker-compose.yml
See #625 for more context.
Requires #641.
> Enable GitHub annotations in templates

- src/cli/lint/external.ts
Per https://github.com/seek-oss/skuba/pull/625#discussion_r735238655.
> Log and continue on lint annotation failure

- .changeset/heavy-seahorses-know.md
- src/cli/adapter/prettier.ts
While poking around the issue of #659 I found this easy optimisation.
> Skip reading unsupported Prettier files

- docs/deep-dives/editors.md
Per internal Slack discussion.
> Document VS Code setup

- .changeset/forty-seas-tell.md
- template/express-rest-api/.buildkite/pipeline.yml
- template/greeter/.buildkite/pipeline.yml
- template/koa-rest-api/.buildkite/pipeline.yml
- template/lambda-sqs-worker-cdk/.buildkite/pipeline.yml
- template/lambda-sqs-worker/.buildkite/pipeline.yml
> Retrieve GitHub token on Test & Lint

- .changeset/many-cooks-melt.md
- .changeset/six-knives-train.md
- docs/development-api/github.md
- src/api/github/environment.ts
- src/api/github/index.ts
> Export GitHub environment helper functions

- src/cli/init/git.ts
- src/utils/git.test.ts
- src/utils/git.ts
This could be used in our Changesets adapter and lint autofixing.
> Add Git commit and push helpers

- src/api/github/checkRun.ts
This is a dangling Markdown link reference.
> Fix weird JSDoc copypasta

- .changeset/polite-zoos-fix.md
- .changeset/popular-eyes-bathe.md
- docs/development-api/github.md
- src/api/github/checkRun.ts
- src/api/github/issueComment.test.ts
- src/api/github/issueComment.ts
- src/api/github/pullRequest.test.ts
- src/api/github/pullRequest.ts
> Add `GitHub.putIssueComment` helper

- src/api/github/index.ts
Classic
These are already all documented but didn't actually exist: https://seek-oss.github.io/skuba/docs/development-api/github.html
> Remember to export stuff

- docs/deep-dives/github.md
As requested by @udaniesalgado.
Gave a full example to get annotations working at SEEK to help new users.
> Update GitHub Annotations Documentation

- docs/development-api/git.md
This is mismatched currently: https://seek-oss.github.io/skuba/docs/development-api/git.html#getownerandrepo
> Fix heading level

- template/koa-rest-api/src/listen.ts
https://github.com/seek-oss/skuba/pull/706/files#r767434410
> Re-register hook in Koa template

- .changeset/wise-ravens-do.md
- src/cli/node.ts
> Fix REPL load

- .changeset/hungry-rocks-pay.md
- .changeset/smooth-kings-look.md
- package.json
- yarn.lock
This revives #440 now that we have a compatible `ts-node-dev@next`.
> Upgrade to ts-node 10

- .changeset/neat-apes-watch.md
- template/express-rest-api/gantry.apply.yml
- template/express-rest-api/gantry.build.yml
- template/koa-rest-api/gantry.apply.yml
- template/koa-rest-api/gantry.build.yml
- SEEK-Jobs/gantry#488
- SEEK-Jobs/gantry#1661
> Ignore deployment alarms and ECR scanning

- .changeset/brave-peas-carry.md
- template/lambda-sqs-worker-cdk/cdk.json
- template/lambda-sqs-worker-cdk/package.json
This is a fix to the [reported issue](https://github.com/seek-oss/skuba/issues/796).
Closes #796.
> Fix progress key in cdk.json

- .changeset/cool-melons-work.md
- .changeset/curvy-papayas-remember.md
- .changeset/purple-balloons-speak.md
- .changeset/purple-candles-retire.md
- docs/development-api/git.md
- src/api/git/commitAllChanges.int.test.ts
- src/api/git/commitAllChanges.ts
- src/api/git/currentBranch.test.ts
- src/api/git/currentBranch.ts
- src/api/git/index.ts
- src/api/git/log.test.ts
- src/api/git/log.ts
- src/api/git/remote.test.ts
- src/api/git/remote.ts
- src/api/github/environment.test.ts
- src/api/github/environment.ts
- src/utils/env.ts
Extracted this to a separate branch for easier reviewing.
> Tweak Git helpers for #800

- package.json
- yarn.lock
https://app.snyk.io/vuln/SNYK-JS-SIMPLEGIT-2434306
> deps: simple-git ^3.5.0

- src/cli/test/reporters/github/index.test.ts
- src/cli/test/reporters/github/index.ts
This should help to troubleshoot validation failures.
Suggested by @samchungy in #832.
> Log last check run on error

- .github/workflows/validate.yml
Another attempt at #830.
https://github.community/t/is-there-a-way-to-tell-if-a-pr-is-from-a-forked-repository/134186
> Try to run validate workflow on forks deux

- README.md
> nitpick the badge

- config/tsconfig.json
- package.json
- yarn.lock
> Remove `skipLibCheck`

- src/utils/wait.test.ts
- src/utils/wait.ts
This could cause the process to hang around until the timeout resolved.
> Clear timeout

- .changeset/cool-buses-give.md
- .changeset/large-swans-join.md
- template/koa-rest-api/package.json
- template/lambda-sqs-worker/src/framework/logging.ts
https://seekchat.slack.com/archives/CDCPCEPV3/p1653606310727419
> Fix Context Logger

- package.json
- yarn.lock
This is now on the stable release channel.
https://github.com/wclr/ts-node-dev/compare/v2.0.0-0...v2.0.0
> deps: ts-node-dev ^2.0.0

- .changeset/beige-pandas-cry.md
- jest-preset.js
- package.json
- yarn.lock
As per internal Slack discussion.
> Add `jest-watch-typeahead` plugin

- template/express-rest-api/README.md
- template/greeter/README.md
- template/koa-rest-api/README.md
- template/lambda-sqs-worker/README.md
- template/oss-npm-package/README.md
- template/private-npm-package/README.md
> Remove Renovate step from README checklist

- template/koa-rest-api/src/api/jobs/postJob.test.ts
- template/koa-rest-api/src/framework/validation.test.ts
- template/lambda-sqs-worker/src/framework/validation.test.ts
Maybe we should get rid of these 🤔
> Update runtype validation snapshots

- .changeset/tender-pianos-tell.md
- .eslintignore
- .gitignore
- .prettierignore
- src/cli/configure/analysis/__snapshots__/project.test.ts.snap
- template/base/_.eslintignore
- template/base/_.gitignore
- template/base/_.prettierignore
- yarn.lock
As discussed in `#typescriptification`.
> Allow `.idea` and `.vscode` ignore overrides

- template/lambda-sqs-worker/package.json
Apparently this has been manually fixed by DefinitelyTyped.
> Drop resolution in template

- template/express-rest-api/package.json
- template/greeter/package.json
- template/koa-rest-api/package.json
- template/lambda-sqs-worker-cdk/package.json
- template/lambda-sqs-worker/package.json
- template/oss-npm-package/_package.json
- template/private-npm-package/_package.json
This is a (temporary?) measure to get CI healthy again.
> template: Pin `@types/node`

- .changeset/curvy-shirts-cry.md
- .changeset/pretty-trains-jog.md
- src/cli/configure/analysis/__snapshots__/project.test.ts.snap
- src/cli/configure/modules/jest.test.ts
- src/cli/configure/modules/jest.ts
- src/cli/configure/modules/tsconfig.test.ts
- src/cli/configure/modules/tsconfig.ts
> Reduce configure clobbering

- .changeset/itchy-rats-beam.md
- jest/transform.js
- jest/transform.test.ts
Transform config can also come in an array 🤷‍♂️
> Fix Jest Transformer

- .changeset/great-paws-tap.md
> Add changeset for #1029

- .changeset/ten-windows-sneeze.md
- src/cli/__snapshots__/lint.int.test.ts.snap
- src/cli/adapter/prettier.ts
> lint: Require package.json to be sorted

- .changeset/honest-readers-applaud.md
- .github/renovate.json5
- template/lambda-sqs-worker-cdk/.buildkite/pipeline.yml
- template/lambda-sqs-worker/.buildkite/pipeline.yml
> Use `renovate-` branch name prefix

- docs/deep-dives/editors.md
As much as vscode is the goat 🐐 . We also need to provide support to the plebs
> Update IDE advice for Webstorm

- src/cli/lint/autofix.test.ts
- src/cli/lint/autofix.ts
> Autofix Renovate presets for real

- .changeset/fair-shrimps-count.md
- src/cli/configure/patchServerListener.test.ts
- src/cli/configure/patchServerListener.ts
- src/cli/format.ts
- src/cli/lint/autofix.ts
- src/cli/lint/index.ts
> RFC: Autofix keep-alive timeout

- .github/renovate.json5
Aligns with seek-oss/rynovate#83.
> Revert Renovate range strategy to "replace"

- .changeset/dry-suns-relate.md
- template/base/.github/CODEOWNERS
As raised by @askoufis on Slack.
> template: Include manifest files in CODEOWNERS

- .changeset/cold-stingrays-smile.md
- package.json
- template/oss-npm-package/_package.json
https://docs.npmjs.com/generating-provenance-statements#using-third-party-package-publishing-tools
https://github.blog/2023-04-19-introducing-npm-package-provenance/
> Use provenance

- .github/workflows/release.yml
- template/oss-npm-package/.github/workflows/release.yml
https://docs.npmjs.com/generating-provenance-statements
Need this perm
> Add id-token permission

- .changeset/light-ears-fold.md
- .changeset/perfect-lamps-wink.md
- src/api/git/currentBranch.int.test.ts
- src/api/git/currentBranch.ts
- src/api/git/findRoot.int.test.ts
- src/api/git/findRoot.ts
- src/api/git/index.ts
- src/api/git/remote.int.test.ts
- src/api/git/remote.ts
- src/cli/configure/patchRenovateConfig.test.ts
- src/cli/configure/patchRenovateConfig.ts
This aims to resolve reported warnings like the following:
```
Failed to patch Renovate config.
Error: Could not find a GitHub remote
```
> Resolve Git root

- .changeset/nine-keys-accept.md
- jest-preset.js
The other option would be to revert to Prettier 2.
> RFC: Disable Prettier snapshot formatting

- .changeset/mighty-buttons-fry.md
> Nitpick changeset

- docs/deep-dives/buildkite.md
- docs/deep-dives/github.md
This defaults to `false` in the v5 plugin.
https://github.com/buildkite-plugins/docker-buildkite-plugin/releases/tag/v5.0.0
> docs: Remove explicit `mount-buildkite-agent`

- .changeset/heavy-buses-tease.md
- src/cli/lint/autofix.test.ts
- src/cli/lint/autofix.ts
https://seekchat.slack.com/archives/CDCPCEPV3/p1694574776656669
> Resolve infinite autofix loop

- src/api/git/commitAllChanges.int.test.ts
- src/api/git/commitAllChanges.ts
Fixes https://github.com/seek-oss/skuba/actions/runs/6362606248/job/17277726040?pr=1276#step:8:49
> Make git paths relative to git root

- config/prettier.js
I had a suspicion I would need to do this so I tested a snapshot on my local and this was erroring
> Require resolve prettier plugin

- __mocks__/sort-package-json.ts
Missed this in the cleanup when I moved to the prettier plugin
> Remove old mock

- .changeset/green-flies-draw.md
- template/lambda-sqs-worker/package.json
- template/lambda-sqs-worker/src/hooks.ts
Not sure when `transformToString()` was added but it works
> Remove @aws-sdk/util-utf8-node from worker template

- .env
- .github/workflows/validate.yml
- CONTRIBUTING.md
- package.json
- yarn.lock
Setting this to run `nr test*` on each new terminal session was getting annoying.
> Use `--env-file` to simplify self-development

- .changeset/orange-moles-yell.md
- docs/cli/init.md
- src/cli/init/getConfig.ts
- src/cli/init/prompts.ts
> Allow defaults in initial prompt

- template/private-npm-package/.releaserc
- template/private-npm-package/README.md
Follows on from #1335 and #1336.
~~I'd like to land this after #1337 so we have more confidence in CI.~~
> Template default branch in private-npm-package

- template/lambda-sqs-worker-cdk/Dockerfile
> Remove stray `yarn package`

- src/cli/configure/getEntryPoint.ts
- src/cli/configure/getProjectType.ts
- src/cli/configure/index.ts
- src/cli/init/getConfig.ts
- src/cli/init/prompts.ts
- src/cli/lint/annotate/index.ts
- tsconfig.json
This one annoys me when it comes to auto importing for this project. If we turn off baseUrl, the IDE will always import relatively.
> Disable tsconfig baseUrl

- .changeset/large-singers-argue.md
- template/lambda-sqs-worker-cdk/infra/__snapshots__/appStack.test.ts.snap
- template/lambda-sqs-worker-cdk/infra/appStack.test.ts
- template/lambda-sqs-worker-cdk/package.json
This is in the docs and lets you add fine-grained assertions on top.
https://docs.aws.amazon.com/cdk/v2/guide/testing.html#testing_snapshot
> Use `aws-cdk-lib/assertions`

- scripts/test-template.sh
- template/lambda-sqs-worker/_.npmrc
```Ghost-written-by: Sam Chung <samc@seek.com.au>```
> Serverless considered shameful

- scripts/test-template.sh
Keep it in the (other) family
https://github.com/seek-oss/skuba/pull/1376#discussion_r1445582103
> Use `pnpm pack`

- scripts/test-template.sh
https://github.com/seek-oss/skuba/commit/4330f6cfae98fbdd1ad77267a685b6e982caad62
> Nit test template script

- .changeset/new-geese-flash.md
- template/express-rest-api/.gantry/dev.yml
- template/express-rest-api/gantry.apply.yml
- template/koa-rest-api/.gantry/dev.yml
- template/koa-rest-api/gantry.apply.yml
Upstreaming something we missed.
> Turn off CloudWatch dashes in dev

- template/express-rest-api/.buildkite/pipeline.yml
- template/greeter/.buildkite/pipeline.yml
- template/koa-rest-api/.buildkite/pipeline.yml
- template/lambda-sqs-worker-cdk/.buildkite/pipeline.yml
- template/lambda-sqs-worker/.buildkite/pipeline.yml
These don't seem especially important to highlight.
> Minimise `pnpm install` log groups in Buildkite

- .github/workflows/release.yml
- .github/workflows/snapshot.yml
- .github/workflows/validate.yml
- template/oss-npm-package/.github/workflows/release.yml
- template/oss-npm-package/.github/workflows/validate.yml
https://github.com/seek-oss/skuba/actions/runs/7712152931?pr=1385
> Resolve Node.js 16 action deprecation warning

- scripts/package.ts
https://github.com/seek-oss/skuba/actions/runs/7792223526/job/21249802203#step:7:13
> Skip changelog linting for preamble

- docs/deep-dives/buildkite.md
- docs/deep-dives/github.md
> Use `propagate-environment` in BK deep dive

- CONTRIBUTING.md
> Clarify snapshots

- .github/workflows/snapshot.yml
- scripts/snapshot-pre-publish.sh
- scripts/snapshot-pre-version.sh
I'm sorry
---
Trying to get snapshots to public as a pre-release version e.g. next-version-branch-date rather than 0.0.0-branch-date so that patches run only if upgrading.
> Horrible hacks

- template/express-rest-api/Dockerfile.dev-deps
- template/greeter/Dockerfile
- template/koa-rest-api/Dockerfile.dev-deps
- template/lambda-sqs-worker-cdk/Dockerfile
- template/lambda-sqs-worker/Dockerfile
> Sort the mounts

- .prettierignore
- docs/deep-dives/pnpm.md
> Prettier Ignore specific sections in deep-dive

- .github/workflows/validate.yml
Duplicated from seek-oss/aws-codedeploy-hooks#36.
> Use fork code path for Dependabot

- .changeset/chatty-pets-hear.md
- template/lambda-sqs-worker/serverless.yml
Alternatively, is this the point at which we deprecate the Serverless template and focus our efforts going forward on the CDK template?
> RFC: Update tagging for Serverless worker template

- .github/workflows/validate.yml
- docs/deep-dives/github.md
https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
> Try to simplify CI

- .changeset/fifty-toys-destroy.md
- .changeset/soft-laws-double.md
- docs/deep-dives/arm64.md
> RFC: Refresh ARM64 guide

- docs/deep-dives/arm64.md
- docs/deep-dives/pnpm.md
Our Jekyll site has a dodgy highlighter :(
I pushed this via `beta` branch to the site to test that it works: https://seek-oss.github.io/skuba/docs/deep-dives/arm64.html
> Fix code diff highlighting

- .github/workflows/release.yml
Superseded by changeset snapshots
> Don't imply existence of beta branch

- .changeset/wild-ants-beg.md
> Add forgotten changeset

- .changeset/changelog.js
Version Packages CI seems to be unhappy
> Fix Unhappy Changelog

- CONTRIBUTING.md
> Update slack channels

- README.md
- docs/cli/init.md
- docs/development-api/git.md
- integration/git/new.json
- packages/eslint-config-skuba/README.md
- src/api/git/reset.int.test.ts
- Update badges to Node.js 18.18
- Say "master" less
> Make a couple miscellaneous meta tweaks

- .changeset/nasty-maps-greet.md
- .github/workflows/release.yml
- .github/workflows/snapshot.yml
- .github/workflows/validate.yml
- template/oss-npm-package/.github/workflows/release.yml
- template/oss-npm-package/.github/workflows/validate.yml
I left our actions in a hanging state (waiting for user input) for a couple hours so we should set a default timeout. I figure 20 minutes is fairly reasonable.
> Set a timeout for our actions

- .changeset/config.json
- .github/workflows/release.yml
- .github/workflows/validate.yml
- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- docs/deep-dives/pnpm.md
- docs/templates/api.md
- docs/templates/barebones.md
- docs/templates/package.md
- docs/templates/worker.md
- packages/eslint-config-skuba/package.json
- scripts/deploy.sh
- site/_config.yml
Fostering a respectful workplace. Closes off #221 and makes Sam's life more difficult in #1497.
> Switch ourselves to main

- .changeset/config.json
- .github/workflows/release.yml
- .github/workflows/validate.yml
- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- docs/deep-dives/pnpm.md
- docs/templates/api.md
- docs/templates/barebones.md
- docs/templates/package.md
- docs/templates/worker.md
- packages/eslint-config-skuba/package.json
- scripts/deploy.sh
- site/_config.yml
I chose wrong here: https://github.com/seek-oss/skuba/pull/1505#issuecomment-2019101042
> Sync main back to master

- .changeset/gentle-suits-live.md
- template/express-rest-api/package.json
- template/koa-rest-api/package.json
I think this is breaking CI in #1513
> template/*-rest-api: Fix lint failure

- .github/renovate.json5
https://docs.renovatebot.com/modules/manager/regex/#required-fields
https://docs.renovatebot.com/configuration-options/#custommanagers
Potential to use this to update the buildkite plugin readme refs
> Attempt to update pnpm version in deep-dive

- .github/renovate.json5
> Match only docs .md files

- .github/renovate.json5
See it working here:
https://github.com/samchungy/renovate-experiments/issues/1
> Renovate Buildkite Plugins in Docs

- docs/deep-dives/pnpm.md
Just compress a couple steps into single commands
> Simplify pnpm migration steps

- .github/workflows/validate.yml
Disables run of checks on successive pushes to the pull request
> Remove duplicate check runs

- .github/workflows/validate.yml
> Revert "Remove duplicate check runs"

- jest.config.ts
Noticed Jest complaining about files in our templates:
> Configure Jest Roots

- docs/deep-dives/pnpm.md
> Update PNPM Migration FAQ

- docs/deep-dives/pnpm.md
- template/lambda-sqs-worker-cdk/infra/__snapshots__/appStack.test.ts.snap
Adjust guide based on feedback from the team.
> Tweak pnpm guide

- docs/deep-dives/arm64.md
- docs/deep-dives/buildkite.md
- template/express-rest-api/README.md
- template/greeter/README.md
- template/koa-rest-api/README.md
- template/lambda-sqs-worker/README.md
- template/oss-npm-package/README.md
- template/private-npm-package/README.md
https://seekchat.slack.com/archives/CA18J5J0L/p1721274541052159
Can I get away without a changeset?
> Rename Builds at SEEK to Buildkite Docs

- .changeset/small-actors-sit.md
- template/lambda-sqs-worker-cdk/.buildkite/pipeline.yml
- template/lambda-sqs-worker-cdk/package.json
Fixes the deploy:hotswap script as raised by @jtadgell.
Also, removes the hotswap step from the pipeline, as you'd probably only ever run this locally.
> Fix CDK Template Script

- docs/deep-dives/pnpm.md
We need to run format twice now, once to ensure .npmrc is moved to the bottom of the file if not already, and then a second time to actually synthesise the file now it's now gitignored, after https://github.com/seek-oss/skuba/pull/1554
> Fix pnpm guide

- .changeset/hot-crews-swim.md
- src/cli/__snapshots__/format.int.test.ts.snap
- src/cli/lint/internalLints/upgrade/patches/8.2.1/index.ts
- src/cli/lint/internalLints/upgrade/patches/8.2.1/intext.ts
- src/cli/lint/internalLints/upgrade/patches/8.2.1/patchDockerCompose.test.ts
- src/cli/lint/internalLints/upgrade/patches/8.2.1/patchDockerCompose.ts
https://github.com/seek-oss/skuba/issues/1553
> Could be worth writing an autofix
🙇
> Remove docker-compose version autofix

- template/lambda-sqs-worker-cdk/infra/__snapshots__/appStack.test.ts.snap
- template/lambda-sqs-worker-cdk/infra/appStack.test.ts
I don't think it's worth changesetting this
> Reduce noise in CDK template snapshots

- .github/workflows/release.yml
- .github/workflows/snapshot.yml
- template/oss-npm-package/.github/workflows/release.yml
Testing switching to using a scoped NPM_TOKEN
> Switch to using the scoped npm token

- packages/eslint-config-skuba/index.js
- packages/eslint-config-skuba/package.json
- pnpm-lock.yaml
- https://github.com/seek-oss/skuba/pull/1537#discussion_r1772462725
- https://github.com/seek-oss/eslint-config-seek/pull/149/
> Clean up `plugins` handling

- src/cli/lint/internalLints/upgrade/patches/8.2.1/collapseDuplicateMergeKeys.test.ts
- src/cli/lint/internalLints/upgrade/patches/8.2.1/collapseDuplicateMergeKeys.ts
> Make beautiful regex even beautifuler

- scripts/test-template.sh
Not sure when this broke running locally but this fixes it
> Fix test-template script

- .changeset/little-carpets-jog.md
- src/cli/lint/autofix.test.ts
- src/cli/lint/autofix.ts
Reverts seek-oss/skuba#1687
Reverting due to https://github.com/seek-oss/rynovate/pull/125 :'(
> Revert "Remove old autofix logic"

- docs/cli/build.md
Hidden feature no longer hidden
> Document Hidden Feature

- .changeset/quick-dragons-punch.md
- template/lambda-sqs-worker-cdk/README.md
- template/lambda-sqs-worker-cdk/infra/__snapshots__/appStack.test.ts.snap
- template/lambda-sqs-worker-cdk/infra/appStack.test.ts
- template/lambda-sqs-worker-cdk/infra/appStack.ts
- template/lambda-sqs-worker-cdk/package.json
Fix / improve a few things for CDK template
- `version` in unit test, in pipeline `version` is always going to be different
- `dd_tags` in unit test, in pipeline we do not get `dd_tags` value
- add missing start command in `package.json`
- add required smoke test configuration step in readme
> improve cdk template

- template/koa-rest-api/src/framework/server.test.ts
Noticed this regression in #1766
> Fix self lint

- packages/eslint-config-skuba/index.js
https://eslint.org/docs/latest/use/configure/configuration-files#configuration-objects
> Add names to ESLint config objects

- template/koa-rest-api/Dockerfile.dev-deps
Thanks @yaojian-seek for the spot
> Add a missed `22`

- pnpm-lock.yaml
- template/express-rest-api/package.json
- template/greeter/package.json
- template/koa-rest-api/package.json
- template/lambda-sqs-worker-cdk/package.json
- template/oss-npm-package/_package.json
- template/private-npm-package/_package.json
Dunno what Changesets is doing in #1729
> Try to manually align `@types/node`

- .changeset/floppy-cycles-beg.md
- src/cli/configure/processing/module.test.ts
- src/utils/copy.test.ts
- src/utils/copy.ts
Resolves https://github.com/seek-oss/skuba/issues/1454
> Log, instead of crashing, on bad template files

- src/cli/configure/index.ts
- src/cli/configure/modules/package.ts
- src/cli/init/getConfig.ts
- src/cli/lint/index.ts
- src/cli/lint/internalLints/noSkubaTemplateJs.ts
- src/cli/lint/internalLints/refreshConfigFiles.ts
- src/cli/lint/internalLints/upgrade/index.ts
- src/utils/logo.ts
- src/utils/packageManager.test.ts
- src/utils/packageManager.ts
Is this slightly more obvious?
> Try to unconfuse package manager commands

- docs/cli/migrate.md
> Add brief note to manually bump `@types/node`

- .changeset/soft-times-happen.md
- src/cli/__snapshots__/format.int.test.ts.snap
- src/cli/__snapshots__/lint.int.test.ts.snap
- src/cli/build/assets.ts
- src/cli/build/esbuild.ts
- src/cli/format.ts
- src/cli/init/index.ts
- src/cli/lint/autofix.ts
- src/cli/lint/eslint.ts
- src/cli/lint/internal.ts
- src/cli/lint/internalLints/detectBadCodeowners.test.ts
- src/cli/lint/internalLints/detectBadCodeowners.ts
- src/cli/lint/internalLints/refreshConfigFiles.test.ts
- src/cli/lint/internalLints/refreshConfigFiles.ts
- src/cli/lint/internalLints/upgrade/index.ts
- src/cli/lint/prettier.ts
- src/utils/logging.ts
I missed a log in the bad codeowners check, which meant it failed your lint without any message 😬
> Clean up logging

- .changeset/slow-teeth-tie.md
- docs/cli/lint.md
- src/cli/format.ts
- src/cli/lint/internal.ts
- src/cli/lint/internalLints/upgrade/index.ts
- src/cli/lint/types.ts
TBH I mainly want this for testing patches locally but there's an argument for it being used by skuba users too
> --force-apply-all-patches

- .changeset/eighty-tools-pull.md
- template/lambda-sqs-worker-cdk/infra/__snapshots__/appStack.test.ts.snap
- template/lambda-sqs-worker-cdk/infra/appStack.ts
> Set queue retention to 14 days

- .changeset/rich-clocks-remember.md
- pnpm-lock.yaml
- template/lambda-sqs-worker-cdk/infra/appStack.ts
- template/lambda-sqs-worker-cdk/package.json
- template/lambda-sqs-worker-cdk/src/app.ts
- template/lambda-sqs-worker-cdk/src/framework/handler.ts
https://github.com/seek-oss/aws-codedeploy-hooks/blob/main/packages/hooks/README.md#islambdahook
> lambda-sqs-worker-cdk: Support expedited deployments

- .changeset/renovate-7f9b936.md
something in our setup is broken
> Fix changeset

- .changeset/upset-flies-allow.md
- src/cli/configure/modules/package.test.ts
- src/utils/packageManager.test.ts
- src/utils/packageManager.ts
> Use pnpm by default

- .changeset/huge-baths-tell.md
- src/cli/configure/modules/jest.test.ts
- src/cli/configure/processing/package.test.ts
- src/cli/lint/internalLints/upgrade/patches/7.3.1/addEmptyExports.test.ts
- src/cli/lint/internalLints/upgrade/patches/7.3.1/patchDockerfile.test.ts
- template/koa-rest-api/src/framework/validation.test.ts
I refuse to review https://github.com/seek-oss/skuba/pull/1930 without this
> Fix some snap formatting after jest upgrade

- .changeset/hip-forks-reply.md
- src/api/git/commitAllChanges.int.test.ts
- src/api/git/currentBranch.int.test.ts
- src/api/git/findRoot.int.test.ts
- src/api/git/getChangedFiles.int.test.ts
- src/api/git/getChangedFiles.ts
- src/api/git/remote.int.test.ts
- src/api/git/reset.int.test.ts
- src/cli/build/assets.int.test.ts
- src/cli/lint/internalLints/detectBadCodeowners.test.ts
- src/cli/lint/internalLints/patchRenovateConfig.test.ts
- src/cli/lint/internalLints/upgrade/patches/10.0.4/removeYarnIgnoreOptionalFlags.test.ts
- src/cli/lint/internalLints/upgrade/patches/10.1.0/stopBundlingInCDKTests.test.ts
- src/cli/lint/internalLints/upgrade/patches/7.3.1/patchDockerfile.test.ts
- src/cli/lint/internalLints/upgrade/patches/8.2.1/collapseDuplicateMergeKeys.test.ts
- src/cli/lint/internalLints/upgrade/patches/8.2.1/moveNpmrcMounts.test.ts
- src/cli/lint/internalLints/upgrade/patches/8.2.1/upgradeESLint.test.ts
- src/cli/migrate/nodeVersion/index.test.ts
> Try to fix autofixes with LFS

- .changeset/eleven-readers-follow.md
- docs/deep-dives/buildkite.md
- docs/deep-dives/github.md
- docs/deep-dives/npm.md
- package.json
- packages/eslint-config-skuba/package.json
- packages/skuba-dive/package.json
- template/express-rest-api/.buildkite/pipeline.yml
- template/express-rest-api/docker-compose.yml
- template/greeter/.buildkite/pipeline.yml
- template/greeter/docker-compose.yml
- template/koa-rest-api/.buildkite/pipeline.yml
- template/koa-rest-api/docker-compose.yml
- template/lambda-sqs-worker-cdk/.buildkite/pipeline.yml
- template/lambda-sqs-worker-cdk/docker-compose.yml
No energy to regex a patch today 😅
> Use `mount-buildkite-agent`

- docs/deep-dives/esm.md
https://devblogs.microsoft.com/typescript/announcing-typescript-5-9-beta/#support-for---module-node20
> Assume we will ESM after TypeScript 5.9

- scripts/test-template.sh
Discovered this in the process of working on #2001.
> Fix `test:template:updateSnapshot` script

- template/express-rest-api/package.json
- template/koa-rest-api/package.json
- template/lambda-sqs-worker-cdk/package.json
Depends on https://github.com/seek-oss/logger/pull/191
> Return to stable `@seek/logger`

- .changeset/chubby-rockets-punch.md
- template/lambda-sqs-worker-cdk/infra/__snapshots__/appStack.test.ts.snap
- template/lambda-sqs-worker-cdk/infra/appStack.test.ts
- template/lambda-sqs-worker-cdk/infra/appStack.ts
- template/lambda-sqs-worker-cdk/package.json
I'm not convinced anyone uses this and requires a workaround to properly use it
> Remove hotswap functionality

- src/cli/format/__snapshots__/format.int.test.ts.snap
- src/cli/lint/internalLints/upgrade/patches/12.3.0/index.ts
- src/cli/lint/internalLints/upgrade/patches/12.3.0/patchApiTokenFromEnvironment.test.ts
- src/cli/lint/internalLints/upgrade/patches/12.3.0/patchApiTokenFromEnvironment.ts
>TEAM
>We care about each other and collaborate to achieve together.
Autofix https://github.com/seek-oss/skuba/pull/2079
> Autofix apiTokenFromEnvironment usage

- docs/development-api/index.md
Mostly fixing the '@' but thought I'd nit at the examples
> Update API docs
