- .changeset/gorgeous-apples-join.md
- src/cli/configure/processing/package.test.ts
- src/cli/configure/processing/package.ts
This was overly aggressive. It matters now because we want to support packages, where this metadata actually has a use.
> Retain proper package.json fields with configure

- .changeset/odd-steaks-fry.md
- README.md
- src/cli/start/http.ts
This only logs the port; it's not worth the potential confusion.
> Remove custom logging support from start

- .github/workflows/validate.yml
This theoretically allows us to accept contributions via fork + PR. GitHub hides secrets (apart from a read-only GITHUB_TOKEN) from forked workflows so there should be no risk.
https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets#using-encrypted-secrets-in-a-workflow
> Run validate on pull requests

- yarn.lock
Among other things, this pulls in a newer `eslint-plugin-import` that no longer complains about ESLint 7.
> Maintain lockfile

- .changeset/pretty-moose-argue.md
- package.json
Package managers like pnpm are "strict" about implicit transitive dependencies; this may help to explain how to get things working in similar environments.
> Declare `@types/jest` as a peer dependency

- .changeset/clever-otters-draw.md
- package.json
- src/cli/configure/analysis/package.ts
- src/cli/configure/analysis/project.test.ts
- src/cli/configure/modules/skubaDive.test.ts
- src/cli/configure/modules/skubaDive.ts
- yarn.lock
This should be more stable than relying on dodgy Yarn 1.x output.
> Use latest-version to get skuba-dive version

- .changeset/heavy-kangaroos-carry.md
- .changeset/olive-zebras-love.md
- src/cli/configure/index.ts
- src/cli/init/index.ts
I can't promise full Yarn 2.x + PnP support, but this is a small step.
> Drop unsupported Yarn 2 flags

- .changeset/gold-phones-sneeze.md
- README.md
- template/koa-rest-api/package.json
- template/koa-rest-api/src/framework/logging.ts
- template/koa-rest-api/src/framework/metrics.ts
- template/koa-rest-api/src/framework/server.ts
- template/lambda-sqs-worker/package.json
- template/lambda-sqs-worker/src/framework/metrics.ts
- Enables us to run integration tests in CI without a token
- Reduces barrier to entry for new `skuba` users
> Remove private deps from built-in templates

- .changeset/breezy-dancers-think.md
- src/cli/init/index.ts
This is super noisy on Yarn 1.x otherwise.
> Restore `--silent` arg for `yarn add`

- .changeset/red-trains-explode.md
- config/eslint.js
- Allows `require('skuba/config/jest').someProperty`
- Allows additional filenames like `jest.config.int.js` and `jest.int.config.js`
> Relax linting on Jest config files

- .changeset/tender-vans-bake.md
- template/koa-rest-api/.gantry/common.yml
- template/koa-rest-api/.gantry/dev.yml
- template/koa-rest-api/.gantry/prod.yml
- template/koa-rest-api/gantry.apply.yml
- template/koa-rest-api/src/config.ts
Defining an application environment that was different to the Gantry environment was potentially confusing, and led to tagging differences between built-in and custom metrics.
> Pass through Gantry environment as ENVIRONMENT

- .changeset/neat-lobsters-suffer.md
- .changeset/pretty-dolls-tap.md
- src/cli/init/getConfig.ts
- src/cli/init/prompts.ts
- src/enquirer.d.ts
Enquirer bundles a prompt type that is a really good fit for us here. This also lets us work around the aggressive `runForm` validation that prevented us from defaulting the org field to SEEK-Jobs.
---
Bonus: some terminals even let you click on the URLs!
> Use snippet prompt for initial details

- src/cli/configure/applyConfiguration.ts
- src/cli/configure/ensureTemplateCompletion.ts
- src/cli/configure/index.ts
- src/cli/init/index.ts
- src/utils/copy.test.ts
- src/utils/copy.ts
The intent here is to support naive string replacements, which could be used to e.g. replace all instances of `@seek/skuba` with plain `skuba`.
> Abstract text processing during file copy

- .changeset/stale-jeans-peel.md
- src/cli/init/git.ts
- src/cli/init/index.ts
- src/utils/exec.ts
We can automatically configure the remote since we now capture GitHub org and repo details. Making some initial commits is another easy win.
> Git more on init

- .changeset/dull-oranges-sparkle.md
- src/skuba.ts
- src/utils/args.test.ts
- src/utils/args.ts
- src/utils/command.test.ts
- src/utils/command.ts
This was hacked around because the command makes sense in kebab-case, but we use camelCase for modules and exports. Previously `buildPackage` was displayed as the canonical command name when you ran `skuba help`, but it wouldn't actually work. This makes `build-package` the actual command and introduces a simple kebab-case -> camelCase conversion that could be used for future commands.
> Fix `build-package` naming under help

- .changeset/cold-ghosts-poke.md
- template/koa-rest-api/src/framework/logging.ts
- template/lambda-sqs-worker/src/app.test.ts
- template/lambda-sqs-worker/src/framework/handler.test.ts
- template/lambda-sqs-worker/src/framework/handler.ts
- template/lambda-sqs-worker/src/framework/logging.ts
Headers are often represented with this capitalisation.
At some point we may have to bite the bullet and ratify aggressive redaction in a package that wraps Pino (e.g. `logger-js`).
> Redact Authorization from logs

- .changeset/tame-mangos-lie.md
- .dockerignore
- src/cli/configure/analysis/__snapshots__/project.test.ts.snap
- template/base/_.dockerignore
The `.git` folder should not be copied into the docker container.
This should improve build speed.
> fix: Ignore git folder

- .changeset/happy-seals-push.md
- src/cli/configure/analysis/__snapshots__/project.test.ts.snap
- template/base/_.dockerignore
Ignore the .gantry folder when copying into the Docker container.
This should decrease build times.
> fix: Ignore gantry folder

- .changeset/famous-carpets-matter.md
- src/cli/configure/analyseConfiguration.ts
- src/cli/configure/analysis/__snapshots__/project.test.ts.snap
- src/cli/configure/getEntryPoint.ts
- src/cli/configure/getProjectType.ts
- src/cli/configure/index.ts
- src/cli/configure/modules/package.test.ts
- src/cli/configure/modules/package.ts
- src/cli/configure/modules/renovate.test.ts
- src/cli/configure/modules/renovate.ts
- src/cli/configure/modules/skubaDive.test.ts
- src/cli/configure/modules/skubaDive.ts
- src/cli/configure/modules/tsconfig.test.ts
- src/cli/configure/modules/tsconfig.ts
- src/cli/configure/testing/module.ts
- src/cli/configure/types.ts
- src/cli/init/getConfig.ts
- src/cli/init/index.ts
- src/cli/init/types.ts
- src/cli/init/writePackageJson.test.ts
- src/cli/init/writePackageJson.ts
- src/enquirer.d.ts
- src/utils/manifest.ts
- src/utils/template.ts
- template/greeter/skuba.template.js
- template/koa-rest-api/skuba.template.js
- template/lambda-sqs-worker/skuba.template.js
- template/private-npm-package/skuba.template.js
This introduces a new `package.json#/skuba/type` field that is used by `skuba configure` to tailor logic based on whether we're dealing with an application or package. This could be extended in future to somehow enable a monorepo type, but it's probably too early to say.
> Store project type to tailor configuration

- docs/eslint.md
- docs/migrating-from-seek-module-toolkit.md
- docs/migrating-from-seek-skuba.md
Spoiler: we'll force a migration to ESLint in `seek-module-toolkit` so that the path from there to `skuba` is smoother.
I wish we had more documentation around the move but I'm hoping this can be community-contributed. I can't make much up off the top of my head.
> Extract ESLint docs

- .changeset/small-penguins-change.md
- template/private-npm-package/README.md
- template/private-npm-package/_package.json
> Align private-npm-package

- jest.setup.ts
- src/cli/configure/types.ts
- template/lambda-sqs-worker/src/framework/logging.ts
- tsconfig.json
This is recommended to flatten the curve and for Babel builds. We won't promote this to the default config just yet.
> Isolate modules internally

- .changeset/blue-pianos-camp.md
- src/cli/configure/modules/package.test.ts
- src/cli/configure/modules/package.ts
These are holdovers from `seek-module-toolkit` and bespoke configs that didn't roll type checking into their `lint` script.
> Remove `test:build` and `test:jest` scripts

- .changeset/spicy-jeans-remember.md
- src/cli/configure/processing/__snapshots__/ignoreFile.test.ts.snap
- src/cli/configure/processing/ignoreFile.test.ts
- src/cli/configure/processing/ignoreFile.ts
This should leave repos migrated from `seek-module-toolkit` and pre-#58 ignore files in a better state instead of littering old patterns everywhere.
> Clean up ignore files during migration

- .changeset/little-balloons-cheat.md
- README.md
- src/cli/init/index.ts
This allows us to properly distribute self-consistent betas.
> Install matching skuba version on init

- .changeset/plenty-garlics-refuse.md
- src/cli/configure/analyseDependencies.ts
- src/cli/configure/analysis/__snapshots__/project.test.ts.snap
- src/cli/configure/analysis/project.test.ts
- src/cli/configure/dependencies/seekDatadogCustomMetrics.test.ts
- src/cli/configure/dependencies/seekKoala.test.ts
- src/cli/configure/dependencies/skuba.test.ts
- src/cli/configure/dependencies/skubaDeps.test.ts
- src/cli/configure/dependencies/skubaDive.test.ts
- src/cli/configure/dependencies/skubaDive.ts
- src/cli/configure/index.ts
- src/cli/configure/modules/package.ts
- src/cli/configure/modules/skubaDive.test.ts
- src/cli/configure/modules/skubaDive.ts
- src/cli/configure/types.ts
This migrates the last of the dependency logic out of the "config" step into the earlier "dependency" step, so the dependency diff should be fully accurate now.
This only implements a simple switch of "package means no dive, application means dive". We can build on this to allow applications to opt-out, as described in #26.
> Move skuba diving to appropriate step

- .changeset/popular-clouds-train.md
- package.json
- src/cli/configure/modules/jest.test.ts
- src/cli/configure/modules/jest.ts
- src/cli/configure/modules/package.test.ts
- src/cli/configure/modules/package.ts
- src/cli/configure/processing/typescript.test.ts
- src/cli/configure/processing/typescript.ts
After many half-hearted attempts, I've finally mustered the will to get TypeScript ASTing. This extracts a blessed list of Jest options from the input `jest.config.js` and merges that with our base config. We also naively set the `--coverage` flag in `package.json#/scripts/test` when we see the `collectCoverage` option.
---
And yes, Jest configuration is _JavaScript_, but this may be a better investment if we end up doing something smart with `.ts` sources in future.
> Migrate select Jest options

- src/cli/configure/modules/renovate.ts
I forgot that I added `initialFiles` to avoid the exact nervousness around order of execution that this module was displaying.
> Simplify Renovate configuration logic

- .changeset/cyan-papayas-swim.md
- README.md
- src/cli/configure/analysis/__snapshots__/project.test.ts.snap
- src/cli/configure/modules/tsconfig.test.ts
- template/base/tsconfig.json
- template/oss-npm-package/tsconfig.json
- template/private-npm-package/tsconfig.json
This makes sense as the default given that `skuba build-package` builds to e.g. `/lib-es2015`.
> Exclude `lib-` directories from compilation

- .changeset/smart-crews-appear.md
- src/cli/configure/index.ts
- src/cli/init/getConfig.ts
- src/cli/init/git.ts
The old copy for these lines assumed that you understood that `skuba` would be installed locally and you had to use e.g. `yarn` or `npx` to point to its CLI.
> Make mentioned commands actually runnable

- .changeset/young-deers-rescue.md
- src/utils/copy.ts
Turns out that this is rather hurtful to `__mocks__` and such.
> Reduce unintended stripping of `_` filename prefix

- .changeset/thirty-bananas-build.md
- src/cli/configure/index.ts
- src/cli/init/index.ts
- src/utils/exec.ts
These are annoying and there's little that users can do about it. Most of these come from e.g. transitive Jest dependencies, and Jest has open issues tracking the migration to supported dependencies.
> Suppress dependency deprecation warnings

- .changeset/rare-apples-know.md
- src/cli/configure/processing/json.test.ts
- src/cli/configure/processing/json.ts
- src/cli/configure/processing/package.test.ts
- src/cli/configure/processing/package.ts
Prettier appears to have some special casing around the formatting of `package.json` files that isn't applied to just any JSON file. This ensures that a `package.json` manipulated via `skuba configure` or `skuba init` will pass Prettier format checking.
> Format `package.json` consistently

- .changeset/light-tomatoes-try.md
- src/cli/configure/modules/renovate.test.ts
- src/cli/configure/modules/renovate.ts
We support the migration of existing SEEK Renovate configurations, which are predominantly stored in JSON format. While JSON5 is fully compatible with JSON, Prettier prefers different formatting with JSON5 files.
> Format Renovate config

- .changeset/large-donuts-teach.md
- src/cli/init/getConfig.ts
- src/cli/init/index.ts
- src/utils/copy.ts
This filename manipulation has haunted me as `copyFiles` gets used in more places. #106 tightened up the matching patterns but a target repository _could_ have some legitimate reason for storing a filename with a prefix of `_.` that would still get chomped.
Instead, only trigger this logic on `skuba init` of a built-in template. There's no reason to do this on `skuba configure`, and external GitHub-hosted templates shouldn't run into the packaging troubles that necessitate a `_package.json`.
> Avoid stripping of `_` filename prefixes

- .changeset/ninety-crabs-tell.md
- src/cli/format.ts
- src/cli/lint.ts
The current calls for ESLint for both checking and fixing linting errors include an explicit list of extensions to check: `js` and `ts`.
An appropriately configured skuba project is able to compile tsx files to js. Typically resolving JSX to React.createElement commands. As it's possible to write and use tsx files I'd like to have eslint run over these files.
This change will include tsx in files that are checked and fixed for eslint.
> Include tsx files in ESLint linting

- .changeset/swift-adults-sell.md
- config/prettier.d.ts
- src/cli/configure/modules/eslint.test.ts
- src/cli/configure/modules/eslint.ts
- src/cli/configure/modules/renovate.ts
- src/cli/configure/processing/json.ts
- src/cli/configure/processing/prettier.ts
- src/cli/configure/processing/typescript.ts
This replaces `extends: [require.resolve('skuba/config/eslint')]` with `extends: ['skuba']`, which is possible now that we have a dedicated shareable config `eslint-config-skuba`.
> Use simple ESLint extends syntax

- .changeset/large-moles-add.md
- src/cli/configure/modules/tsconfig.test.ts
- src/cli/configure/modules/tsconfig.ts
This is purely cosmetic, but `skuba configure` was leaving old skubified `tsconfig.json`s like:
```json
{
"exclude": ["lib*/**/*", "lib/**/*"]
}
```
> Remove duplicate lib exclusions from tsconfig.json

- .changeset/neat-toes-burn.md
- README.md
- jest-preset.d.ts
- src/api/jest/index.test.ts
- src/api/jest/index.ts
- src/cli/configure/analysis/__snapshots__/project.test.ts.snap
- src/cli/configure/processing/record.test.ts
- src/cli/configure/processing/record.ts
- src/cli/configure/processing/typescript.test.ts
- src/cli/configure/processing/typescript.ts
- src/index.ts
- template/base/jest.config.js
This concatenates array options, unlike Jest's built-in `preset` support which discards the original array elements.
> Add `Jest.mergePreset` helper function

- .changeset/clean-cooks-behave.md
- jest-preset.js
I was deceived by `@jest/types`. It seems this is a CLI-only option.
This was throwing ugly warnings but didn't otherwise hurt anyone.
> Remove passWithNoTests Jest option

- .changeset/eighty-monkeys-rush.md
- template/lambda-sqs-worker/serverless.yml
- template/lambda-sqs-worker/src/services/aws.ts
Replaces `keepAlive` property of https agent
> Use connection reuse environment variable in Lambda

- CONTRIBUTING.md
- README.md
This also drops the duplicated "development" section from the README.
> Separate out "running locally" section

- .changeset/fluffy-moose-cry.md
- template/koa-rest-api/src/framework/logging.ts
- template/lambda-sqs-worker/src/framework/logging.ts
This appears to be a thing in Gaxios / Node Fetch errors. There's lots of internal state that isn't suitable for logs.
> Redact `err.config.agent` path from error logs

- .changeset/chilled-cougars-melt.md
- template/koa-rest-api/Dockerfile
This gives you cacheable dependency targets and makes the final runtime stage look less scary as it doesn't copy directly from `unsafe`.
> Add intermediate Dockerfile stages

- .changeset/calm-buckets-cheat.md
- .changeset/sweet-colts-boil.md
- template/koa-rest-api/README.md
- template/lambda-sqs-worker/README.md
- template/lambda-sqs-worker/serverless.yml
This was raised by @BryceKK as we don't document how to do this.
To keep it a simple single-variable matter, we now default the `VERSION` environment variable to `local` if it is not supplied. I generally don't like defaults but this one is mostly harmless, and we do a similar thing with `BUILDKITE_COMMIT`.
I took the opportunity to make our READMEs slightly less bad, but they are still pretty bad.
> Document local Lambda deployment

- .changeset/lucky-coins-dream.md
- .changeset/ninety-wasps-wave.md
- template/koa-rest-api/package.json
- template/koa-rest-api/src/api/jobs/postJob.test.ts
- template/koa-rest-api/src/api/jobs/postJob.ts
- template/koa-rest-api/src/framework/validation.test.ts
- template/koa-rest-api/src/framework/validation.ts
- template/koa-rest-api/src/testing/types.ts
- template/koa-rest-api/src/types/jobs.ts
- template/lambda-sqs-worker/src/app.ts
- template/lambda-sqs-worker/src/framework/validation.test.ts
- template/lambda-sqs-worker/src/framework/validation.ts
- template/lambda-sqs-worker/src/services/jobScorer.ts
- template/lambda-sqs-worker/src/testing/types.ts
- template/lambda-sqs-worker/src/types/jobScorer.ts
- template/lambda-sqs-worker/src/types/pipelineEvents.ts
This removes Yup from the Koa template. Per #151, Yup is too generous in coercing inputs by default, and its strict mode does not support the `stripUnknown` feature that I actually like in Yup.
This also updates the Lambda template with the latest in Runtypes:
- Use the default `checkFilter` as it is easier to comprehend than the manual `filter` and `validate` functions
- Import using `import * as t` to avoid collisions with built-in types
> Switch to new-age Runtypes

- .changeset/cyan-years-exercise.md
- template/koa-rest-api/gantry.apply.yml
- template/lambda-sqs-worker/serverless.yml
I'm not sure why I only added this to the Lambda template.
> Keep AWS SDK connections alive in Koa template

- .changeset/new-lions-shout.md
- scripts/test-template.sh
- template/koa-rest-api/src/api/jobs/getJobs.test.ts
- template/koa-rest-api/src/api/jobs/postJob.test.ts
- template/koa-rest-api/src/app.test.ts
- template/koa-rest-api/src/framework/server.test.ts
- template/koa-rest-api/src/framework/validation.test.ts
- template/koa-rest-api/src/testing/server.ts
Don't start the server and avoid the need to stop it.
> app.callback()
> Return a callback function suitable for the http.createServer() method to handle a request. You may also use this callback function to mount your Koa app in a Connect/Express app.
> feat: Simplify supertest-koa bootstrap

- .changeset/cuddly-mayflies-perform.md
- template/koa-rest-api/.buildkite/pipeline.yml
Matches the production concurrency group configuration.
> fix(koa-rest-api): Use per Gantry environment concurrency group in dev

- .changeset/old-baboons-rescue.md
- .github/workflows/validate.yml
This uses GitHub's new `workflow_run` event to sequence our Validate action to run after the Release action on the default branch. We would previously run into race conditions when we released a new version, as Validate would try to run against a version that was in the process of being released.
Resolves #110.
> Sequence Validate action after Release

- .changeset/wet-zebras-enjoy.md
- template/oss-npm-package/README.md
- template/oss-npm-package/src/index.ts
- template/private-npm-package/README.md
- template/private-npm-package/src/index.ts
Scoped module names were triggering `tsdoc-at-sign-in-word`.
> Avoid TSDoc linting errors on package init

- docs/migrating-from-seek-module-toolkit.md
I can't think of an especially elegant solution here as anyone who cloned a repo from the smt days will be stuck with that hook. A postinstall that deletes the Git hook would be the nuclear option.
> Document Git hook cleanup

- .changeset/plenty-tables-impress.md
- src/cli/configure/analyseConfiguration.ts
- src/cli/configure/index.ts
- src/cli/configure/modules/tsconfig.test.ts
- src/cli/configure/modules/tsconfig.ts
- src/cli/configure/testing/module.ts
- src/cli/configure/types.ts
A number of our older packages don't seem to retain comments in the compiled TypeScript. This makes the first configure (i.e. when migrating from another toolkit) default to retaining comments.
> Retain package comments on first configure

- .changeset/heavy-starfishes-build.md
- docs/migrating-from-seek-module-toolkit.md
- src/cli/configure/modules/package.test.ts
- src/cli/configure/modules/package.ts
- template/oss-npm-package/_package.json
- template/private-npm-package/_package.json
This is something that should be expected to _just work_ and it didn't. JSON deserves to be a special case as it doesn't require packaging hacks as described in our migration documentation; it can be properly resolved and bundled by TypeScript's built-in `resolveJsonModules`.
https://github.com/seek-oss/skuba/blob/master/docs/migrating-from-seek-module-toolkit.md#building
> Include JSON files in package bundles

- .changeset/seven-rules-brake.md
- template/lambda-sqs-worker/src/framework/logging.ts
Plain `requestId` was a bit ambiguous as we also have concepts like an `X-Request-Id` header.
> Qualify `awsRequestId` log field

- .changeset/forty-students-exercise.md
- src/cli/configure/index.ts
This is causing errors on `skuba configure`.
```
Error: Cannot find module 'utils/validation'
```
> Fix bad import in configure

- .changeset/lovely-owls-matter.md
- .changeset/lucky-beds-shave.md
- src/cli/buildPackage.ts
- src/cli/lint.ts
- src/utils/error.ts
- src/utils/exec.ts
This regressed at some point without us noticing.
---
Before:
```
[object Object],[object Object],[object Object]
```
After:
> Improve concurrently error output

- .changeset/good-singers-provide.md
- template/lambda-sqs-worker/package.json
The Lambda runtime includes its own version of the SDK, but this ensures a matching version and circumvents bundling issues like we're currently seeing with the latest SDK and Serverless.
> Include aws-sdk in Lambda bundle

- .changeset/chilled-bats-argue.md
- src/cli/start/index.ts
This is the default with e.g. sku and I could've sworn that it was working this way in earlier versions of skuba. We could surface a separate command to run typechecking interactively, but that's probably not the responsibility of `start`.
> Do not typecheck with `start`

- .changeset/thick-seas-notice.md
- template/koa-rest-api/Dockerfile
- template/koa-rest-api/package.json
- template/koa-rest-api/src/listen.ts
The benefit of `koa-cluster` with less than 1 vCPU hadn't been properly established. On Fargate AWS will expose multiple hyperthreads but according to our TAM they'll be throttled to use less than 100% CPU usage in total.
Benchmarking across three high-volume Indirect services with a variety of workloads has confirmed this. Their response latency, CPU usage, etc. remain unaffected but their memory usage is reduced 20-40%. This should also improve the efficiency of any in-memory caches the services have.
This keeps the same basic layout as before but with a stub `listen.ts` taking the place of `koa-cluster`. This still allows easy use of `koa-cluster` and reduces forward/backwards compatibility issues with existing Skuba apps.
> Remove koa-cluster from template

- rich-books-confess.md
- template/express-rest-api/gantry.apply.yml
- template/koa-rest-api/gantry.apply.yml
Adds lower default memory and CPU values for Koa apps.
As @etaoins mentioned elsewhere, the higher Gantry defaults make sense without knowing what the image/runtime will be, e.g a JVM app that may need more memory just to start up.
For skuba where we know the runtime is Node, the lowest available Fargate options seem like a sane default.
> feat(rest api): Add default CPU and memory settings

- .changeset/short-ladybugs-brush.md
- template/greeter/Dockerfile
This aligns with the Lambda template and provides a generally useful `dev-deps` stage to target for e.g. ECR caching.
> Align greeter Dockerfile stages

- .changeset/two-trees-own.md
- template/express-rest-api/docker-compose.yml
- template/greeter/docker-compose.yml
- template/koa-rest-api/docker-compose.yml
- template/lambda-sqs-worker/docker-compose.yml
- template/lambda-sqs-worker/package.json
This should be generally faster across the pipelines, especially for Gantry services that already have this covered with `gantry build`. A caveat is that the Lambda deploy step may take a bit longer, but it's probably good to have a safer npm `deploy` script and we know that we need to revisit the speed of that pipeline soon anyway.
> Skip pre-build in Docker Compose service

- .changeset/chilled-meals-hunt.md
- template/lambda-sqs-worker/serverless.yml
From https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sns-subscription.html#cfn-sns-subscription-region this field is only required for cross region subscriptions. The current value is the default implicit behavior.
> fix(lambda-sqs-worker): Remove region from subscription example snippet

- .changeset/olive-melons-rush.md
- .changeset/silly-seahorses-tickle.md
- .changeset/yellow-papayas-behave.md
- README.md
- package.json
- src/cli/start/index.ts
- src/utils/args.test.ts
- src/utils/args.ts
- template/express-rest-api/package.json
- template/greeter/package.json
- template/koa-rest-api/package.json
- yarn.lock
This allows you to use `skuba start` with IDE debuggers.
> Support Node.js debugging options

- .changeset/stupid-dolphins-tap.md
- README.md
- scripts/test-template.sh
- src/cli/init/getConfig.ts
- src/cli/init/prompts.ts
- src/cli/init/types.ts
- src/enquirer.d.ts
- template/base/.github/CODEOWNERS
The Snippet prompt looked elegant, but was slightly confusing in practice and glitched out on copy+paste. Instead, use a more traditional form input.
- Team name is now optional; closes #149.
- Copy+paste now works; closes #229.
> Rework initial init prompt

- .changeset/old-roses-carry.md
- template/lambda-sqs-worker/.buildkite/pipeline.yml
The preceding `docker-ecr-cache` plugin already logs in to ECR to cache the image.
> Remove redundant `ecr` plugin from Lambda template

- src/cli/lint.test.ts
This test file serves to validate TypeScript syntax support in our ESLint and Prettier linting dependencies. It's dodgy because it's really only marked up as a Jest file for ease of test case structuring and to exclude it from the bundle.
> Add dodgy lint test cases

- README.md
This makes it less confusing for SEEK Asia engineers who are not able to view seek-jobs/gantry, and addresses #282.
> Use official doc URL instead of repo for Gantry

- .changeset/proud-impalas-learn.md
- .changeset/shiny-cougars-greet.md
- README.md
- src/cli/start/http.ts
- template/express-rest-api/Dockerfile
- template/express-rest-api/package.json
- template/express-rest-api/src/app.ts
- template/express-rest-api/src/config.ts
- template/express-rest-api/src/framework/logging.ts
- template/express-rest-api/src/listen.ts
The template wasn't respecting the PORT environment variable provided by a Gantry deployment, and wasn't compatible with `skuba start`.
This fixes those issues and introduces some boilerplate config and logging code that can be extended in future.
> Fix server listener and port in Express template

- .changeset/cuddly-pillows-push.md
- .changeset/giant-foxes-move.md
- template/express-rest-api/package.json
- template/greeter/package.json
- template/koa-rest-api/package.json
- template/lambda-sqs-worker/package.json
- template/oss-npm-package/_package.json
- template/private-npm-package/_package.json
I've been umming and ahhing on the right approach here, as I like a fairly unopinionated `test` script into which the user can pass their desired flags.
Practically speaking, we have some other tooling like our package publishing pipeline which presumes that the `test` script is suitable for exhaustive CI testing. `test:watch` should be a reasonable compromise for local testing, and already has some SEEK precedence with ~46 `package.json` results returned from a GitHub search.
> Tweak template test scripts

- .changeset/kind-wombats-care.md
- src/cli/build/babel.ts
It looks like this no longer works without an explicit argument.
https://babeljs.io/docs/en/options#sourcemaps
> Fix Babel `--out-dir requires filenames` error

- .changeset/large-melons-shout.md
- template/koa-rest-api/package.json
- template/koa-rest-api/src/framework/server.test.ts
- template/koa-rest-api/src/framework/server.ts
- Limit request logging to errors
- Remove `err` boilerplate that is now handled by Koala
> Tweak Koa request logging

- .changeset/stale-keys-sell.md
- CONTRIBUTING.md
- package.json
- scripts/postbuild.sh
- tsconfig.json
- yarn.lock
See changeset. Currently we'd only compile to ESM for browser usage, which isn't relevant to skuba.
If it's feasible to drop CommonJS on the Node.js side in future, we can switch across to ESM in one fell swoop rather than bundling both module resolutions.
> Remove ESM from bundle

- .changeset/late-carrots-speak.md
- .changeset/light-files-nail.md
- .changeset/strange-candles-count.md
- .changeset/thick-moons-float.md
- README.md
- package.json
- src/cli/node.ts
- src/cli/start.ts
- src/index.ts
- src/register.ts
- src/skuba.ts
- src/utils/command.ts
- src/wrapper.ts
- yarn.lock
See changesets and README for full details. Closes #84.
---
`skuba node` runs a TypeScript file; it's like a one-off `skuba start`. Unlike start, it gives you a REPL when you omit the command line entry point rather than falling back to the entry point in `package.json`.
This PR also adds some secret sauce to automatically register the `src` module alias when you're running under `skuba node` or `skuba start`. This means that you only need a runtime module alias resolver like `import skuba-dive/register` at the top of production entry points; local scripts can be run with little fanfare using the skuba commands.
---
Notes:
- I considered calling the command `skuba exec`, but that sounds a bit awkward when it supports opening a REPL.
- You may be wondering why don't we just use …
> Implement node wrapper

- .changeset/curvy-drinks-guess.md
- .changeset/eleven-garlics-punch.md
- .changeset/eleven-lobsters-fly.md
- README.md
- src/cli/configure/analysis/__snapshots__/project.test.ts.snap
- src/cli/configure/modules/jest.test.ts
- src/cli/configure/modules/jest.ts
- src/cli/configure/modules/package.test.ts
- src/cli/configure/modules/package.ts
- src/cli/configure/processing/typescript.test.ts
- src/cli/configure/processing/typescript.ts
- src/utils/copy.test.ts
- template/base/jest.config.ts
New repositories will be initialised with a TypeScriptified file. Existing repositories can use `skuba configure` to be migrated over.
Closes #233
> Use `jest.config.ts`

- .changeset/mean-rice-film.md
- src/cli/configure/index.ts
- src/cli/init/index.ts
- src/utils/exec.ts
If a Yarn install command fails due to connectivity issues, we should provide actionable advice on next steps to the user.
> Handle offline scenarios more gracefully

- .changeset/wet-books-live.md
- src/cli/configure/modules/package.test.ts
- src/cli/configure/modules/package.ts
This avoids awkward crashes on `yarn install`:
```text
error Workspaces can only be enabled in private projects.
```
---
Closes #199
> Ensure workspaced `package.json` is private

- .changeset/wise-fans-join.md
- template/express-rest-api/Dockerfile
- template/koa-rest-api/Dockerfile
Distroless images present a smaller attack surface as they ship without a package manager, shell and the like. These have been promoted out of experimental status since I last checked.
https://github.com/GoogleContainerTools/distroless/tree/master/nodejs
> Use Distroless runtime images

- .changeset/empty-jobs-drive.md
- template/express-rest-api/gantry.apply.yml
- template/koa-rest-api/gantry.apply.yml
I expect this to be spicy but it seems like a more sensible default for typical Node.js HTTP APIs.
> Supply custom autoscaling policy to Gantry

- .changeset/thick-bees-ring.md
- src/cli/test.ts
This is something that Jest itself does in its `bin/jest`:
https://github.com/facebook/jest/blob/master/packages/jest-cli/bin/jest.js
Typically this doesn't do anything interesting but some libraries look at `NODE_ENV` to tweak their behaviour under Jest.
An example (and the motivation for this) is `new ApolloServer`. Normally it attaches an event listener to `process.exit` to clean up various internal handles. However, if this happens too many times it causes Node to spew warnings:
> MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added to [process]. Use emitter.setMaxListeners() to increase limit
To work around this Apollo won't attach an event listener if `NODE_ENV` === `test`. Unfortunately because Skuba isn't using the Jest wrapper this is …
> Set NODE_ENV to `test` in Jest

- .changeset/eight-mails-pay.md
- template/lambda-sqs-worker/package.json
- template/lambda-sqs-worker/serverless.yml
- template/lambda-sqs-worker/src/app.ts
- template/lambda-sqs-worker/src/hooks.ts
- template/lambda-sqs-worker/src/services/jobScorer.ts
- template/lambda-sqs-worker/src/services/pipelineEventSender.ts
This is missing a bit of documentation; I have a follow-up PR to uplift the API and worker READMEs. We've tested this pattern with an internal service and I've also ensured that the template is deployable from scratch.
---
Relates to #116, which can be closed once we add appropriate documentation to the API templates.
> Add smoke testing to Lambda template

- .changeset/swift-ads-arrive.md
- jest-preset.js
These were getting picked up post-TypeScriptification.
> Exclude Jest `config.ts` files from coverage

- .changeset/modern-grapes-crash.md
- .changeset/nasty-carpets-rescue.md
- package.json
- src/cli/node.ts
- src/cli/start.ts
- src/skuba.ts
- src/utils/args.test.ts
- src/utils/args.ts
- src/wrapper/index.ts
- yarn.lock
`skuba node` and `skuba start` weren't even making an attempt to propagate command-line arguments to `process.argv` in the underlying entry point script. This is a dealbreaker for the former command as it's fairly common to want to run arbitrary scripts that take arguments, e.g. `skuba node cli/dropAllTables.ts --force`.
To maintain compatibility some tricky parsing is required, because we currently route arguments to a bunch of different places. The wrapper interplay is somewhat simplified by moving some arguments to environment variables.
I also uncovered that `ts-node` doesn't like Node.js inspector options, so we now run scripts using plain `node`. What could go wrong with all these layers upon layers?
> Fix `process.argv` propagation

- .changeset/purple-points-wash.md
- docs/buildkite.md
- src/cli/lint.ts
- src/utils/exec.ts
This is sad but it's not uncommon to run into issues with typical instance sizing at SEEK. This should also alleviate contention on the shared publishing agents.
If we want to be clever in future we could inspect `BUILDKITE_AGENT_META_DATA_AWS_INSTANCE_TYPE`.
> Run processes serially on Buildkite

- .changeset/popular-drinks-remember.md
- template/lambda-sqs-worker/serverless.yml
Per https://github.com/serverless/serverless/pull/8279
> Remove custom Serverless variable syntax

- .changeset/silly-knives-prove.md
- template/lambda-sqs-worker/serverless.yml
- template/lambda-sqs-worker/src/config.ts
Why:
1. `AWS_REGION` is the reserved runtime environment variable in AWS lambda.
2. AWS_SDK looks for AWS_REGION by default
3. one less environment configuration in serverless.yml
References:
https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/setting-region.html#setting-region-environment-variable
https://docs.aws.amazon.com/lambda/latest/dg/configuration-envvars.html
> Retire REGION in favour of AWS_REGION

- .changeset/good-eggs-jog.md
- template/express-rest-api/.gantry/common.yml
- template/express-rest-api/gantry.apply.yml
- template/express-rest-api/src/config.ts
- template/express-rest-api/src/framework/logging.ts
- template/koa-rest-api/.gantry/common.yml
- template/koa-rest-api/gantry.apply.yml
- template/koa-rest-api/src/config.ts
- template/koa-rest-api/src/framework/logging.ts
- template/lambda-sqs-worker/src/config.ts
- template/lambda-sqs-worker/src/framework/logging.ts
> Drop region parameterisation

- .changeset/nice-apricots-turn.md
- README.md
- src/cli/format.test.ts
- src/cli/format.ts
- src/cli/lint.test.ts
- src/cli/lint.ts
- src/utils/args.test.ts
- src/utils/args.ts
This can clue you in on which files ESLint and Prettier are formatting and linting, which can in turn inform your `.eslintignore` and `.prettierignore` files.
> Support debug flag on format and lint

- .changeset/perfect-eyes-approve.md
- .changeset/short-baboons-mix.md
- src/api/jest/index.ts
Makes it easier to set without having to merge with a separate object, e.g https://github.com/SEEK-Jobs/indie-awsk-redux/pull/23 
~I'm not sure if there is a way to set this if it isn't configurable via the skuba preset.~
> Expose testTimeout in jest preset options

- yarn.lock
Semantic Release has upgraded to npm v7, which resolves a bunch of transitive vulnerabilities:
- https://app.snyk.io/vuln/SNYK-JS-SSRI-1085630
- https://app.snyk.io/vuln/SNYK-JS-YARGSPARSER-560381
- https://app.snyk.io/vuln/npm:mem:20180117
> Relock `@semantic-release/npm`

- .changeset/green-bats-admire.md
- .changeset/seven-hotels-attend.md
- template/lambda-sqs-worker-cdk/.buildkite/pipeline.yml
- template/lambda-sqs-worker-cdk/cdk.json
**What?**
1. Pass the correct npm token arg name to the build container
2. Limit update to events only to prevent output being flooded by single characters during cdk deploy
> fix CDK worker template

- .changeset/lucky-pants-peel.md
- template/lambda-sqs-worker-cdk/.buildkite/pipeline.yml
- template/lambda-sqs-worker-cdk/Dockerfile
**Why?**
Prior to this change, the built code was packaged with the docker image. Since the image is ECR cached on `package.json` and `yarn.lock`, stale code will be deployed if there are no changes to either file.
**What?**
This change adds a build command before CDK deploy to ensure the latest built code gets picked up and deployed. It also removes the unnecessary code build in the image.
> Build lambda-sqs-worker-cdk before deploy

- .changeset/loud-feet-pump.md
- src/cli/configure/analyseConfiguration.ts
- src/cli/configure/analysis/diff.ts
- src/cli/configure/analysis/package.ts
- src/cli/configure/getEntryPoint.ts
- src/cli/configure/getProjectType.ts
- src/cli/configure/modules/jest.ts
- src/cli/configure/modules/skubaDive.ts
- src/cli/configure/modules/tsconfig.ts
- src/cli/configure/processing/ignoreFile.ts
- src/cli/configure/processing/javascript.ts
- src/cli/configure/processing/json.ts
- src/cli/configure/processing/package.ts
- src/cli/configure/processing/record.ts
- src/cli/configure/processing/typescript.ts
- src/cli/init/prompts.ts
- src/cli/lint.test.ts
- src/cli/test.ts
- src/register.ts
- src/utils/manifest.ts
- template/koa-rest-api/src/framework/server.ts
- template/lambda-sqs-worker/src/services/pipelineEventSender.ts
Neither skuba nor the affected templates here would be run in an ES3 environment.
> Banish `typeof undefined` syntax

- .github/renovate.json5
skuba has pretty intense requirements for renovation; most notably, it bundles templates that need to be tagged and upgraded using different rules. We've outlasted the usefulness of inherited defaults and our frankenstein config stopped working entirely a month ago, per #426.
This tries to vastly simplify a copy of the old base config.
> Handcraft a Renovate config

- .github/renovate.json5
This should be intentionally set to `range` to avoid pinning as seen in #439 and #441. Our templates are fully careted so that newly initialised repos get the latest semver minor and patch versions.
> Fix template range strategy

- .changeset/gentle-ads-attend.md
- template/lambda-sqs-worker/serverless.yml
This was defaulting to 1024 MiB, which is overkill.
> Set memory for Lambda smoke test hook to 128 MiB

- .changeset/curly-deers-sort.md
- template/koa-rest-api/src/api/smokeTest.ts
When loading a smoke test URL in a browser (e.g. from a Datadog synthetics alert) it's impossible to tell a 2xx from a 5xx.
This includes a simple message to indicate the smoke test is happy.
> Include success message in smoke test body

- .changeset/clean-needles-remember.md
- template/express-rest-api/package.json
- template/greeter/package.json
- template/koa-rest-api/package.json
- template/lambda-sqs-worker-cdk/infra/__snapshots__/appStack.test.ts.snap
- template/lambda-sqs-worker-cdk/package.json
- template/lambda-sqs-worker/package.json
- template/oss-npm-package/_package.json
- template/private-npm-package/_package.json
A clean install of `@jest/types` is currently failing because it specifies a `@types/node` range of `*`, and the latest v16 release removes some globals that Jest depends on.
This is a hack to get CI healthy again, until `@jest/types` is properly patched: https://github.com/facebook/jest/pull/11645
> Force `@jest/types` resolution in templates

- .changeset/short-geese-yawn.md
- package.json
- scripts/test-template.sh
- template/express-rest-api/.buildkite/pipeline.yml
- template/express-rest-api/.gantry/common.yml
- template/express-rest-api/skuba.template.js
- template/koa-rest-api/.buildkite/pipeline.yml
- template/koa-rest-api/.gantry/common.yml
- template/koa-rest-api/skuba.template.js
The region values for Gantry are currently hardcoded to ap-southeast-2, but I'd like to encourage all APAC teams to use skuba so parameterising the region would be nice. 
I guessed this is a patch change based on https://github.com/seek-oss/skuba/commit/985ff9a73cf079882efe7f81e45679e8e0a1f7d1
> Parameterise region in Gantry templates

- .changeset/nasty-zebras-share.md
- template/express-rest-api/package.json
- template/greeter/package.json
- template/koa-rest-api/package.json
- template/lambda-sqs-worker-cdk/package.json
- template/lambda-sqs-worker/package.json
- template/oss-npm-package/_package.json
- template/private-npm-package/_package.json
It makes more sense for us to track the LTS version.
I've also updated the carets ranges because why not.
> Use @types/node@14

- .changeset/nine-fishes-swim.md
- package.json
- template/express-rest-api/package.json
- template/greeter/package.json
- template/koa-rest-api/package.json
- template/lambda-sqs-worker-cdk/package.json
- template/lambda-sqs-worker/package.json
- template/oss-npm-package/_package.json
- template/private-npm-package/_package.json
- yarn.lock
Jest 27.1 is compatible with newer versions of `@types/node`.
> Remove `@types/node` resolution override

- .changeset/wet-penguins-switch.md
- template/lambda-sqs-worker-cdk/Dockerfile
- template/lambda-sqs-worker/Dockerfile
The workers don't need to run `yarn install` after this step so we might as well remove the yarn cache associated with it.
In my testing -> this reduced the size of images by half
> ci: remove yarn cache for worker dev deps image

- .changeset/chilled-vans-grow.md
- .changeset/silent-pugs-fetch.md
- template/lambda-sqs-worker-cdk/.buildkite/pipeline.yml
- template/lambda-sqs-worker/.buildkite/pipeline.yml
I'm pretty sure this was unintentionally omitted as we already do this on a bunch of repos internally. Caught by @samchungy.
> Prime dev ECR cache in Lambda Buildkite pipelines

- .github/workflows/release.yml
- package.json
- scripts/deploy.sh
Our README is too long and you can easily get lost in it. I'm planning to pull it apart into multiple pages and include more user guide-like content which will tie in better to our Tech Onboarding initiatives.
A starting point is to deploy our existing Markdown documentation pages to GitHub Pages in CI/CD. I'm still undecided on whether it's worth us wrapping this up in a full-blown sku app for SEEK styling.
> Deploy docs to GitHub Pages

- scripts/deploy.sh
My `cp`ing was not evidently not portable enough, so we were losing all styling on merges to the default branch.
> Fix doc deployment in CI

- CHANGELOG.md
- scripts/deploy.sh
Changesets doesn't like us mangling with the source CHANGELOG.md. See this brokenness: https://github.com/seek-oss/skuba/pull/496/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4ed
---
I went this route because I'm not seeing an obvious way to configure how Changesets actually inserts into CHANGELOG.md, only formatting the individual entries beforehand: https://github.com/atlassian/changesets/blob/main/docs/modifying-changelog-format.md
> Add changelog frontmatter during deploy

- CONTRIBUTING.md
While this doesn't perform global linkage like `npm link`, its setup is almost instantaneous compared to an arduous install process with the npm command.
> Recommend `yarn link` for local integration

- .changeset/changelog.js
- .changeset/config.json
- package.json
- yarn.lock
The `changelog-github` preset was a bit too noisy.
https://github.com/seek-oss/skuba/blob/1bb70463583be41bc45ed5a3ae4fb2b3efabbe18/CHANGELOG.md
---
Here's the proposed change: https://seek-oss.github.io/skuba/CHANGELOG.html
> Generate more minimal changelogs

- .changeset/.prettierrc.js
- .changeset/blue-suits-tie.md
- .changeset/changelog.js
- .changeset/chilled-dots-melt.md
- .changeset/chilled-vans-grow.md
- .changeset/giant-sloths-cross.md
- .changeset/good-lizards-appear.md
- .changeset/light-islands-begin.md
- .changeset/nine-fishes-swim.md
- .changeset/quick-plants-peel.md
- .changeset/short-baboons-leave.md
- .changeset/silent-pugs-fetch.md
- .changeset/silly-deers-draw.md
- .changeset/sour-stingrays-doubt.md
- .changeset/stale-numbers-carry.md
- .changeset/sweet-spies-beam.md
- .changeset/tender-ads-cover.md
- .changeset/twelve-monkeys-cough.md
- .changeset/wet-penguins-switch.md
- CONTRIBUTING.md
This makes it easier to use changeset-default formatting. We override the Prettier config to accept double quotes in the `.changeset` directory, and bold the commit title scope during changelog generation rather than requiring everyone to manually type out the asterisks.
> Make it easier to add changesets

- CHANGELOG.md
I'm mulling over the possibility of parsing the changelog to render e.g. per-template history on the doc site. This fixes up the formatting of a few historical commit title scopes.
> Fix some historical changelog entries

- src/cli/format.int.test.ts
We lucked out by listing the exit code-setting test case last, but this will avoid future confusion.
> Reset exit code between tests

- .changeset/itchy-cobras-bow.md
- .changeset/tender-ads-cover.md
- docs/cli/build.md
- docs/cli/lint.md
- docs/deep-dives/buildkite.md
- src/cli/buildPackage.ts
- src/cli/lint.test.ts
- src/cli/lint.ts
- src/cli/lint/types.ts
- src/utils/args.test.ts
- src/utils/args.ts
- src/utils/exec.ts
Previously, we had a Buildkite-specific hack to propagate the BUILDKITE environment variable in order to run these commands serially. This is potentially surprising behaviour, particularly if the consumer is propagating the variable for some other purpose.
That point will become less hypothetical once skuba adds built-in support for Buildkite annotations. We replace the inference with a very explicit flag.
> build-package, lint: Add `--serial` flag

- .changeset/ten-snails-act.md
- .github/workflows/validate.yml
- jest.config.int.ts
- jest.config.ts
- package.json
- src/api/jest/index.ts
Our integration tests mess with some `process` globals so they need to be `--runInBand`. This is a bit annoying for the rest of the tests though, so we keep an integration-less `yarn test` that allows for parallelism.
This also fixes a loop that can occur when `--watch`ing the integration tests due to the resulting file I/O in the `integration` directory.
> Reorganise test scripts

- .github/workflows/validate.yml
- CHANGELOG.md
- package.json
- scripts/deploy.sh
- scripts/package.ts
- src/cli/init/prompts.ts
- src/utils/template.ts
- yarn.lock
These are now available on each page under this section:
https://seek-oss.github.io/skuba/docs/templates/
---
This feature relies on a certain level of structure being applied to our templates and changelogs. To that end, we now validate in CI that template configuration is internally consistent and require all changelog entries to have a scope.
> Generate per-template changelogs

- scripts/package.ts
This broke the site deployment in CI. I was testing this locally on Node.js 16 and even there it's marked as experimental, so we use `fs-extra.copy` for now.
> Avoid `fs.promises.cp`

- integration/base/fixable/tsconfig.json
- integration/base/ok/tsconfig.json
- integration/base/unfixable/tsconfig.json
`tsc` was spending a bunch of time churning through internal TypeScript definitions. We don't really care about this for the purposes of our integration tests.
> Speed up lint integration

- docs/templates/index.md
- scripts/package.ts
This was an excuse to fix a missing `[packages]` link in our documentation, and a typo in our package script.
> Output when each template was added

- .changeset/shy-colts-warn.md
- src/cli/lint/eslint.ts
- src/cli/lint/prettier.ts
- src/utils/worker.ts
We were getting some real sketchy output:
```
(node:212) UnhandledPromiseRejectionWarning: Error: EBADF: bad file descriptor, close
(Use `node --trace-warnings ...` to show where the warning was created)
(node:212) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:212) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js …
```
> Handle worker thread errors more gracefully

- .changeset/serious-candles-do.md
- src/api/jest/index.test.ts
- src/api/jest/index.ts
This change allows npm packages that are targeted to the browser to run their tests using jsdom.
Details in changeset.
> Allow testEnvironment to be passed to Jest.mergePreset

- .changeset/bright-oranges-heal.md
- src/api/jest/index.test.ts
- src/cli/configure/processing/record.test.ts
- src/cli/configure/processing/record.ts
closes: https://github.com/seek-oss/skuba/issues/593
As discussed in https://github.com/seek-oss/skuba/issues/593 this chance could be considered a breaking change. However, if this hasn't been intended functionality and users wouldn't be expecting it, it seems fine to make this change as a patch.
Alternatively we could deprecate this call and create a new method like `withDefaults`.
Details in Changeset.
> No-longer mutate underlying defaults when calling Jest.mergePreset

- .changeset/serious-candles-do.md
This is valid as a `minor`, but I'm leaning `patch` to make it seamless to automerge. The change is simple and only affects TypeScript types.
> Reduce #592 to a patch

- .changeset/clever-masks-develop.md
- template/lambda-sqs-worker/serverless.yml
These are a bit cheaper and a bit faster than the x86 Lambdas:
<https://aws.amazon.com/blogs/aws/aws-lambda-functions-powered-by-aws-graviton2-processor-run-your-functions-on-arm-and-get-up-to-34-better-price-performance/>
The underlying Lambda architecture should be invisible to typical TypeScript Lambdas. Indirect Apply has switched over all of their Lambdas, only encountering difficulty with DataDog/serverless-plugin-datadog#184.
> Switch `lambda-sqs-worker` template to ARM64

- .changeset/lemon-apes-battle.md
- src/wrapper/functionHandler.ts
These appeared like `fn(a, , , d)`, which was a bit weird.
> Add a `?` placeholder for unnamed function args

- .changeset/cuddly-forks-give.md
- docs/deep-dives/github.md
- docs/development-api/github.md
- src/api/github/checkRun.test.ts
- src/api/github/checkRun.ts
- src/api/github/environment.test.ts
- src/api/github/environment.ts
- src/api/github/index.ts
- src/cli/lint/annotate/github/index.test.ts
- src/cli/lint/annotate/github/index.ts
1. Source GIt metadata from Git repo.
This reduces the number of Buildkite environment variables required to use `GitHub.createCheckRunFromBuildkite`, while adding the basic `BUILDKITE` variable for symmetry with `Buildkite.annotate`.
2. Move Buildkite specifics out of the GitHub development API and into the lint adapter.
This provides a cleaner generic interface for our API. We also generalise the adapter code so we can support other CI platforms like GitHub Actions.
> Decouple GitHub.createCheckRun from Buildkite

- src/api/github/checkRun.ts
- src/cli/adapter/eslint.ts
- src/cli/adapter/prettier.ts
- src/utils/logging.ts
This also decouples it from the logger as it can function as a pure standalone function.
> Reuse pluralise function

- .changeset/wet-carrots-argue.md
- .gitignore
- .prettierignore
- src/cli/__snapshots__/format.int.test.ts.snap
- src/cli/__snapshots__/lint.int.test.ts.snap
- src/cli/configure/refreshIgnoreFiles.ts
- src/cli/format.ts
- src/cli/lint/index.ts
Closes #637.
This should be the minimum required to release #645 without users committing `.eslintcache`s to Git.
> Sync ignore files on format and lint

- .changeset/olive-ghosts-battle.md
These will likely require a good number of consumers to re-format their code. This kind of thing will be smoother once we land #644, but that will still require consumers to enable Buildkite write access to their repos.
> Bump prominence of ESLint rule changes

- .changeset/shiny-cows-add.md
- src/cli/adapter/prettier.test.ts
- src/cli/adapter/prettier.ts
> Fix file descriptor warnings

- package.json
- yarn.lock
This is a bit of a weird one, but I've seen my local linked installation of skuba occasionally crack the shits when Jest imports `jsonfile/utils` from a wrongly hoisted major version. This should have no effect on external consumers.
> Add a direct dep on `jsonfile`

- jest.config.int.ts
- jest.config.ts
- src/wrapper/main.test.ts
- Mock out console logging in a test module
- Set `coveragePathIgnorePatterns` in our configs
- Invert `displayName`; our `jest.config.int.ts` actually runs all tests, which is preferable over multiple independent configs for collecting coverage
> Clean up few testing things

- .changeset/funny-snails-share.md
- docs/cli/run.md
- package.json
- src/register.ts
- yarn.lock
Note that this does not modify our typical `skuba-dive/register` runtime hook. The drift between the two may be a bit puzzling in the time being, but it's somewhat rare for production applications to include `tsconfig.json` in their final bundle or container. Alignment should eventually come as we investigate shifting over to `esbuild`, which supports compile-time `tsconfig-paths` resolution.
> Register `tsconfig-paths` for development

- .changeset/mighty-eagles-rush.md
- jest-preset.js
- jest/moduleNameMapper.js
- jest/moduleNameMapper.test.ts
- jest/transform.js
- package.json
> Support `tsconfig.json` paths in Jest

- .changeset/stupid-pets-explain.md
- template/lambda-sqs-worker-cdk/.buildkite/pipeline.yml
- template/lambda-sqs-worker-cdk/docker-compose.yml
- template/lambda-sqs-worker-cdk/package.json
Did these things in https://github.com/SEEK-Jobs/asia-jobs-data-migrator in order to get it working:
1. Fixed the yarn test step in buildkite (it passes locally)
2. Fixed errors where node_modules weren't being included in the lambda
3. fixed the weird logs in cicd on deploying for cdk
> Fix lambda-sqs-worker-cdk template

- .changeset/brown-bananas-repair.md
- template/koa-rest-api/.gantry/dev.yml
- template/koa-rest-api/.gantry/prod.yml
- template/koa-rest-api/Dockerfile
- template/koa-rest-api/gantry.apply.yml
- template/koa-rest-api/package.json
- template/koa-rest-api/src/listen.ts
- template/koa-rest-api/src/tracing.ts
This brings https://opentelemetry.io/ support, which can be enabled via gantry config (deploys another sidecar that collects the data). According to @bernos it's here to stay and should no longer be considered an experimental feature. Yet has to be widely announced. 
All traces can be viewed in "Technology Platforms" DD org.
This PR is a first step - one template only - koa app.
> Add OpenTelemetry support for Koa template

- .changeset/strong-sloths-live.md
- template/lambda-sqs-worker-cdk/cdk.json
- template/lambda-sqs-worker-cdk/infra/__snapshots__/appStack.test.ts.snap
- template/lambda-sqs-worker-cdk/infra/appStack.test.ts
- template/lambda-sqs-worker-cdk/infra/appStack.ts
- template/lambda-sqs-worker-cdk/infra/index.ts
- template/lambda-sqs-worker-cdk/package.json
https://docs.aws.amazon.com/cdk/v2/guide/migrating-v2.html
Resolves #708.
> Migrate to AWS CDK v2

- .changeset/dull-ravens-reflect.md
- jest/moduleNameMapper.js
While Node.js 12 is going out of support soon, this was an unintended breaking change.
> Restore Node.js 12 compatibility

- .changeset/clean-dingos-compare.md
- package.json
- src/cli/init/git.ts
- yarn.lock
`isomorphic-git` doesn't implement SSH. Closes #736.
> Fix GitHub template cloning

- .changeset/gorgeous-apricots-cross.md
- template/lambda-sqs-worker/serverless.yml
Use the fancy smancy new `params` feature. Produces a much cleaner template 💎 
https://www.serverless.com/framework/docs/guides/parameters
`default` didn't have to be used but I thought it was a good example of how it can be used.
I guess overall `custom` should be used more for plugins.
> Use new Serverless params

- template/koa-rest-api/README.md
Typo was introduced as part of #334, it was fixed in the express api template but not the koa one.
> Fix eskew typo in koa-rest-api readme

- .changeset/big-actors-heal.md
- jest/moduleNameMapper.js
- package.json
> Require Node.js 14.18+

- .changeset/shaggy-jobs-breathe.md
- package.json
- template/express-rest-api/Dockerfile
- template/koa-rest-api/Dockerfile
- template/lambda-sqs-worker-cdk/infra/__snapshots__/appStack.test.ts.snap
- template/lambda-sqs-worker-cdk/infra/appStack.ts
- template/lambda-sqs-worker/serverless.yml
We can get rid of the stack trace support in skuba-dive in favour of this Node.js CLI flag. This is stable in Node.js 14.18 which we require as of #760.
- https://github.com/seek-oss/skuba-dive#register
- https://nodejs.org/api/cli.html#cli_enable_source_maps
Closes #399.
> Use `--enable-source-maps`

- .changeset/three-beers-poke.md
- template/lambda-sqs-worker/serverless.yml
Use `provider.environment` to reduce repetition in the config
> Reduce Repetition of Environment variables

- .changeset/gentle-dogs-melt.md
- template/lambda-sqs-worker/serverless.yml
```
Starting with v3.0, the "variablesResolutionMode" option is now useless. You can safely remove it from the configuration
More info: https://serverless.com/framework/docs/deprecations/#VARIABLES_RESOLUTION_MODE
```
> Remove Serverless `variablesResolutionMode`

- .changeset/early-humans-cheat.md
- package.json
- src/cli/configure/analysis/__snapshots__/project.test.ts.snap
- src/cli/configure/modules/package.test.ts
- src/cli/configure/modules/package.ts
- src/cli/node.ts
- src/cli/start.ts
- template/express-rest-api/.env
- template/express-rest-api/package.json
- template/greeter/package.json
- template/koa-rest-api/.env
- template/koa-rest-api/package.json
- template/lambda-sqs-worker/.env
- template/lambda-sqs-worker/package.json
- yarn.lock
This is a minor convenience over repeated `ENVIRONMENT=local` prefixes.
> node, start: Support `.env`

- .changeset/popular-vans-film.md
- src/cli/adapter/eslint.ts
We got bitten by seek-oss/eslint-config-seek#68.
Example: https://github.com/seek-oss/skuba/runs/5490668838?check_suite_focus=true#step:6:10
> Suppress `eslint-plugin-react` warning

- .changeset/lazy-ants-brush.md
- .github/workflows/codeql-analysis.yml
- .github/workflows/release.yml
- .github/workflows/validate.yml
- template/oss-npm-package/.github/workflows/release.yml
- template/oss-npm-package/.github/workflows/validate.yml
- https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
- https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
> Lock down GitHub workflows

- .github/workflows/release.yml
It looks like #802 didn't do the trick. In theory this means that the actual push will use `seek-oss-ci` now and trigger workflow runs.
- https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow
- https://github.com/seek-oss/skuba/pull/798/commits/11060cbdcb1bcc88e1251601a84fb195a00b1379
> Try supplying the seek-oss-ci token to checkout

- .github/workflows/release.yml
I got "Publish to npm" working nicely in #809 but inadvertently broke the subsequent "Deploy to GitHub Pages" step 🙃
> Restore release `contents` permission

- .github/workflows/validate.yml
These try to reference the to-be-published version which doesn't yet exist on the npm registry.
Resolves ❌ on #798.
> Skip integration on release PR

- .changeset/.prettierrc.js
- .changeset/brave-peas-carry.md
- .changeset/bright-rivers-hear.md
- .changeset/brown-experts-tease.md
- .changeset/changelog.js
- .changeset/cool-melons-work.md
- .changeset/curvy-papayas-remember.md
- .changeset/lazy-ants-brush.md
- .changeset/lemon-buttons-move.md
- .changeset/old-points-brush.md
- .changeset/purple-balloons-speak.md
- .changeset/purple-candles-retire.md
- .changeset/red-cycles-care.md
- .changeset/spicy-gifts-smash.md
- CONTRIBUTING.md
- package.json
We shouldn't need to worry about the Changesets bot producing double quoted Markdown files now that we push linting autofixes.
> Restore reason to changeset formatting

- .changeset/cuddly-weeks-shop.md
- src/cli/test/reporters/github/annotations.test.ts
- src/cli/test/reporters/github/annotations.ts
- src/cli/test/reporters/github/index.test.ts
> fix: strip ansi from Jest error annotations

- .changeset/honest-boxes-talk.md
- src/cli/configure/refreshIgnoreFiles.ts
- src/cli/lint/autofix.test.ts
- src/cli/lint/autofix.ts
- src/cli/lint/external.ts
- src/cli/test/reporters/github/index.ts
- src/utils/error.ts
- src/utils/worker.ts
I have one repo that's failing on the following, and it's a bit annoying to track down:
```console
Failed to annotate results.
TypeError: Cannot read properties of null (reading 'split')
```
> Make warning logs more verbose

- .github/workflows/validate.yml
Secrets are not available to forks, so the empty `token` was failing in #829.
> Try to run validate workflow on forks

- docs/deep-dives/buildkite.md
- docs/deep-dives/github.md
This is less tedious than having to constantly maintain a list of environment variables that skuba uses.
> Encourage `propagate-environment` usage

- docs/deep-dives/buildkite.md
Looks like this is required when `mount-buildkite-agent: false`.
> List `BUILDKITE_AGENT_ACCESS_TOKEN`

- package.json
- yarn.lock
This papers over the following vulnerability:
https://app.snyk.io/vuln/SNYK-JS-ASYNC-2441827
We shouldn't be impacted given we don't use the ejs CLI.
mde/ejs#645
> Specify async resolution

- .changeset/honest-apes-vanish.md
- template/express-rest-api/.buildkite/pipeline.yml
- template/greeter/.buildkite/pipeline.yml
- template/koa-rest-api/.buildkite/pipeline.yml
- template/lambda-sqs-worker-cdk/.buildkite/pipeline.yml
- template/lambda-sqs-worker/.buildkite/pipeline.yml
Our projects should aim for a shorter duration for testing and linting. Taking longer than 10 minutes usually indicates a command or request has hung and will indefinitely hog the build agent, so we define a timeout.
> Time out Buildkite test steps after 10 minutes

- .changeset/brave-owls-join.md
- template/private-npm-package/.buildkite/pipeline.yml
The "npm" agent queue is no longer updated. Instead, the "npm2" queue is used for new repositories. See https://github.com/SEEK-Jobs/gutenberg#installing-on-your-repository
> Update build agent queue

- .changeset/brave-owls-join.md
- .changeset/six-worms-jump.md
- .changeset/tasty-steaks-count.md
- src/cli/adapter/eslint.ts
- src/cli/lint/annotate/github/eslint.test.ts
- src/cli/lint/annotate/github/index.test.ts
- src/cli/lint/autofix.test.ts
- src/cli/lint/autofix.ts
- src/cli/lint/external.ts
1. Skip when ESLint reports no fixable issues
2. Detect ESLint warnings instead of just errors
> Improve autofixing

- package.json
- yarn.lock
We no longer have a vulnerable transitive dep via `semantic-release`.
> Remove `ansi-regex` resolution

- .changeset/loud-kiwis-mate.md
- template/lambda-sqs-worker/serverless.yml
https://www.serverless.com/framework/docs/providers/aws/guide/deploying/#
```
Direct deployments are faster and have no downsides (unless you specifically use the generated change sets). They will become the default in Serverless Framework 4.
```
> Change deployment method to `direct`

- .changeset/olive-worms-run.md
- README.md
- template/koa-rest-api/package.json
- template/koa-rest-api/src/api/jobs/getJobs.ts
- template/koa-rest-api/src/api/jobs/postJob.ts
- template/koa-rest-api/src/framework/logging.ts
- template/koa-rest-api/src/framework/metrics.ts
- template/koa-rest-api/src/framework/server.test.ts
- template/koa-rest-api/src/framework/server.ts
- template/koa-rest-api/src/listen.ts
- template/koa-rest-api/src/testing/logging.ts
This might be a little radical but overall improves the DX and allows users to not need to worry about passing a context object around and/or a context logger around the codebase.
Some local testing confirms `x-request-id` is still present:
Performance hit of ~1.75% according to this which is negligible
https://github.com/nodejs/node/issues/34493#issuecomment-845094849
> feat: use `AsyncLocalStorage` to track logger context

- .changeset/sharp-ads-clean.md
- template/lambda-sqs-worker/serverless.yml
This perm is only needed if we configure asynchronous invocation and use the `onError` configuration but SQS is a synchronous invocation and SQS handles the dead-lettering itself.
> Remove Unnecessary Serverless Permission

- .changeset/rich-spoons-exist.md
- package.json
- src/cli/test/reporters/github/annotations.test.ts
- src/cli/test/reporters/github/annotations.ts
- yarn.lock
I think the "Test suite failed to run" headline here could be useful. The indentation looks a bit annoying though; should I dedent the paragraph?
> Prefer verbose failure message in exec annotations

- .changeset/strong-chefs-wonder.md
- template/express-rest-api/README.md
- template/greeter/README.md
- template/koa-rest-api/README.md
- template/lambda-sqs-worker/README.md
> Fix README links to ARM64 guide

- docs/about.md
- docs/cli/index.md
- docs/cli/test.md
- docs/deep-dives/buildkite.md
- docs/deep-dives/github.md
- package.json
- template/greeter/README.md
- yarn.lock
To stop myself from messing these up and having to create PRs like #913. I'm not sure if involved Markdown linting is worth bundling in skuba itself, but we can locally benefit from `remark-lint` in the meantime.
I also looked into `markdownlint` and `textlint` but couldn't readily find an equivalent rule.
> Catch link definition and reference mismatches

- .changeset/rare-walls-draw.md
- template/lambda-sqs-worker/.buildkite/pipeline.yml
Noticed one of my repos working fine without this.
Looks like they disable interactivity when the process.env.CI environment variable is detected so this is no longer needed.
https://github.com/serverless/utils/pull/162
> Remove tty from serverless template

- .changeset/bright-actors-sneeze.md
- .eslintignore
- .prettierignore
- src/cli/configure/analysis/__snapshots__/project.test.ts.snap
- template/base/_.eslintignore
- template/base/_.prettierignore
Add ignore cdk.out directory linting rule.
`yarn format` or `yarn lint` will probably trigger node heap out of memory issues otherwise.
> make linter ignore cdk.out directory

- .changeset/twenty-pigs-sparkle.md
- package.json
- src/cli/configure/analysis/__snapshots__/project.test.ts.snap
- src/cli/configure/ensureTemplateCompletion.ts
- src/cli/configure/processing/package.test.ts
- src/cli/configure/processing/package.ts
- yarn.lock
This uses [sort-package-json](https://github.com/keithamus/sort-package-json).
> ### How does it sort?
>
> It sorts using [`sort-object-keys`](http://github.com/keithamus/sort-object-keys). It sorts using the well-known keys of a package.json. For the full list check the [default rules](./defaultRules.md). It sorts sub-keys too - sometimes by a well-known order, other times alphabetically. The initial order was derived from the [package.json docs](https://docs.npmjs.com/files/package.json) with a few extras added for good measure.
Re: #107, sorting the `scripts` key [can also be enabled](https://github.com/keithamus/sort-package-json/blob/master/defaultRules.md#scripts). It says only the scripts in that list are sorted, but I tested with non-standard ones and it still worked — see latest …
> Sort `package.json` based on the well-known package.json keys

- .changeset/neat-parents-jump.md
- .changeset/pink-gorillas-repair.md
- .changeset/thin-kings-teach.md
- template/koa-rest-api/package.json
- template/koa-rest-api/src/api/jobs/postJob.test.ts
- template/koa-rest-api/src/api/jobs/postJob.ts
- template/koa-rest-api/src/framework/validation.test.ts
- template/koa-rest-api/src/framework/validation.ts
- template/koa-rest-api/src/testing/types.ts
- template/koa-rest-api/src/types/jobs.ts
- template/lambda-sqs-worker-cdk/infra/appStack.ts
- template/lambda-sqs-worker-cdk/infra/index.ts
- template/lambda-sqs-worker-cdk/package.json
- template/lambda-sqs-worker-cdk/shared/context-types.ts
- template/lambda-sqs-worker/package.json
- template/lambda-sqs-worker/src/app.ts
- template/lambda-sqs-worker/src/framework/validation.test.ts
- template/lambda-sqs-worker/src/framework/validation.ts
- template/lambda-sqs-worker/src/services/jobScorer.ts
- template/lambda-sqs-worker/src/testing/types.ts
- template/lambda-sqs-worker/src/types/jobScorer.ts
- template/lambda-sqs-worker/src/types/pipelineEvents.ts
Closes #983.
Replace Runtypes with Zod in templates:
- koa-rest-api
- lambda-sqs-worker
- lambda-sqs-worker-cdk
> Replace Runtypes with Zod in starter templates

- .changeset/hot-kiwis-crash.md
- integration/base/ok/package.json
- integration/base/unfixable/package.json
- package.json
- src/cli/__snapshots__/format.int.test.ts.snap
- src/cli/adapter/prettier.ts
- template/express-rest-api/package.json
- template/greeter/package.json
- template/koa-rest-api/package.json
- template/lambda-sqs-worker-cdk/package.json
- template/lambda-sqs-worker/package.json
- tsconfig.json
> format: Sort `package.json`

- .changeset/thick-ducks-relax.md
- docs/deep-dives/arm64.md
- template/express-rest-api/Dockerfile
- template/express-rest-api/Dockerfile.dev-deps
- template/greeter/Dockerfile
- template/koa-rest-api/Dockerfile
- template/koa-rest-api/Dockerfile.dev-deps
- template/lambda-sqs-worker-cdk/Dockerfile
- template/lambda-sqs-worker/Dockerfile
Thoughts welcome.
While we don't make it easy to build our templated Dockerfiles locally (at least until we can land #968), but we currently punish x86 holdouts by requiring them to emulate ARM. This should still default to ARM on the ARM64 build agents and deployment targets that we prescribe but allows for flexibility via the `BUILDPLATFORM` Docker built-in.
https://docs.docker.com/build/building/multi-platform/#building-multi-platform-images
> Support AMD64 Docker builds via `BUILDPLATFORM`

- template/koa-rest-api/src/framework/validation.ts
- template/lambda-sqs-worker/src/framework/validation.ts
Resolves https://github.com/seek-oss/skuba/issues/1023
Currently this generic is a little naive and when used it returns the input type of the Zod Type. With basic Zod Types this works as the input type equals the output type but when used in conjunction with zod effects(transform, preprocess) this type becomes incorrect because the input is different to the output.
Before:
After:
Since this isn't released I shouldn't need a changeset right?
> Fix Zod Type Validators

- docs/deep-dives/arm64.md
- template/express-rest-api/Dockerfile
- template/koa-rest-api/Dockerfile
I was hoping that this global would always be available, but it looks like Gantry does not currently supply it when building images.
> Define BUILDPLATFORM fallback for API templates

- template/express-rest-api/Dockerfile.dev-deps
- template/greeter/Dockerfile
- template/koa-rest-api/Dockerfile.dev-deps
- template/lambda-sqs-worker-cdk/Dockerfile
- template/lambda-sqs-worker/Dockerfile
This seems safer given I seem to have observed some presumably old versions of Docker Compose not supplying this value.
> Add BUILDPLATFORM fallbacks everywhere

- .changeset/eighty-bikes-grow.md
- template/lambda-sqs-worker/package.json
Wasn't sure if we wanted to default to layers, so this at least documents the two options.
> Declare dd-trace dependency

- .changeset/purple-readers-collect.md
- template/express-rest-api/.gantry/common.yml
- template/express-rest-api/.gantry/dev.yml
- template/express-rest-api/.gantry/prod.yml
- template/express-rest-api/gantry.apply.yml
- template/koa-rest-api/.gantry/common.yml
- template/koa-rest-api/.gantry/dev.yml
- template/koa-rest-api/.gantry/prod.yml
- template/koa-rest-api/gantry.apply.yml
Set an environment value instead of relying on `'{{.Environment}}'` which is actually the gantry environment name. This was fairly problematic for us when moving Gantry environments given the classroom tells you to create an environment which isn't just "dev" or "prod"
https://backstage.myseek.xyz/docs/default/component/gantry/v1/classroom/step-07/
> Use environment value

- .changeset/red-llamas-explain.md
- src/api/git/commitAllChanges.ts
- src/api/git/getChangedFiles.int.test.ts
- src/api/git/getChangedFiles.ts
- src/api/git/index.ts
- src/api/github/push.ts
- src/cli/lint/autofix.test.ts
- src/cli/lint/autofix.ts
Follows on from #1072 and additionally prevents `.npmrc` mishaps.
> Exclude internal files from autofix commits

- .changeset/big-files-wave.md
- src/cli/configure/analysis/__snapshots__/project.test.ts.snap
- template/base/_.gitignore
Reverts #1072 given #1074 achieves the same result without having to change consumer `.gitignore`s.
> Revert "Ignore `Dockerfile-incunabulum` from Git"

- src/cli/configure/processing/typescript.ts
https://github.com/seek-oss/skuba/actions/runs/3801200255/jobs/6465414295#step:7:176
```
DeprecationWarning: 'createExportAssignment' has been deprecated since v4.8.0. Decorators are no longer supported for this function. Callers should switch to an overload that does not accept a 'decorators' parameter.
```
https://github.com/seek-oss/skuba/actions/runs/3801200255/jobs/6465414295#step:7:211
```
DeprecationWarning: 'createImportDeclaration' has been deprecated since v4.8.0. Decorators are no longer supported for this function. Callers should switch to an overload that does not accept a 'decorators' parameter.
```
> Handle TypeScript deprecations

- .changeset/khaki-drinks-warn.md
- docs/cli/run.md
- package.json
- src/wrapper/http.ts
- src/wrapper/main.test.ts
- src/wrapper/requestListener.ts
- src/wrapper/testing/fastifyRequestListener.ts
- yarn.lock
Tested on my upcoming template:
https://github.com/samchungy/test-fastify-template/pull/1
> Add `skuba start` fastify support

- .changeset/forty-spies-tie.md
- package.json
- src/cli/adapter/eslint.ts
- yarn.lock
The motivation for this is that I would like to optionally configure YAML sorting in a shared configuration repository.
Refs:
- seek-oss/eslint-config-skuba#173
- seek-oss/eslint-config-skuba#174
> Bundle `eslint-plugin-yml`

- .changeset/fair-shrimps-count.md
- template/express-rest-api/src/listen.ts
- template/koa-rest-api/src/listen.ts
The default Node.js server keep alive timeout is set to 5 seconds. However, the Gantry default ALB idle timeout is 30 seconds. This would lead to the occasional issues where the sidecar would throw `proxyStatus` 502 errors while trying to talk to your node application as it would believe that the socket is still open. AWS recommends setting an application timeout larger than the ALB idle timeout.
A more detailed explanation can be found in the below links
https://docs.aws.amazon.com/elasticloadbalancing/latest/application/application-load-balancers.html#connection-idle-timeout
https://nodejs.org/docs/latest-v18.x/api/http.html#serverkeepalivetimeout
So far it has completely removed all 502 errors from the products-api and hirer graphql api
> Set the keep alive timeout to 31 seconds

- .changeset/chilled-spiders-drive.md
- src/cli/lint/autofix.test.ts
- src/cli/lint/autofix.ts
I thought that excluding the `added` state would be enough 🤦.
> lint: Avoid committing `.npmrc` changes

- integration/base/fixable/a/a/a.mjs
- integration/base/fixable/a/a/a.mts
- package.json
- src/cli/__snapshots__/format.int.test.ts.snap
- src/cli/__snapshots__/lint.int.test.ts.snap
- src/cli/adapter/eslint.ts
- yarn.lock
As of v7, ESLint is a bit more friendly:
> ESLint will now lint files with extensions other than `.js` if they are explicitly defined in `overrides[].files` - no need to use the `--ext` flag!
So I added a few new files to verify that it still works without providing a list of extensions. You'll notice a few integration tests failing with this message:
```
<random>/a/a/a.mjs
0:0  error  Parsing error: ESLint was configured to run on `<tsconfigRootDir>/a/a/a.mjs` using `parserOptions.project`: /users/rmate/work/skuba/integration/lint/fixable-bd1e312d13bfc2883c3abec50ef3784eb5e55fe52034b08ce2df4892971d4ce6/tsconfig.json
However, that TSConfig does not include this file. Either:
- Change ESLint's list of included files to not include this file
- Change that TSConfig to include this file
- …
```
> Don't pass explicit list of extensions and let ESLint infer them from the config

- .changeset/nasty-dryers-end.md
- docs/cli/run.md
- src/wrapper/main.test.ts
- src/wrapper/requestListener.ts
- src/wrapper/testing/httpServerRequestListener.ts
Apollo Server 4 changed how you interact with koa and as a result you now have to export a httpServer instance.
eg. `export = httpServer`
https://github.com/apollo-server-integrations/apollo-server-integration-koa
This adds support for exporting a `httpServer` instance.
> Add http server support

- .changeset/cyan-knives-drop.md
- template/lambda-sqs-worker/src/app.test.ts
- template/lambda-sqs-worker/src/app.ts
- template/lambda-sqs-worker/src/framework/handler.test.ts
- template/lambda-sqs-worker/src/framework/handler.ts
- template/lambda-sqs-worker/src/testing/logging.ts
The "Function succeeded" log message was changed from `info` to `debug`
to reduce the amount of unnecessary logs in production.  
The message will still be logged in dev environments but at a `debug`
level.
The "Function succeeded" log message was retained as it is part of unit-testing
the handler.
> template: Change some lambda worker info logs to debug to reduce unneeded production logging

- .changeset/forty-hornets-argue.md
- config/tsconfig.json
Make `noUnusedLocals` and `noUnusedParameters` false.
These two values are set as `true` in SEEK's tsconfig.
Skuba is already using Seek's ESLint config which has a [rule](https://eslint.org/docs/latest/rules/no-unused-vars) which works for both function and types.
We do not need both tools to do the same thing. ESLint has better support for ignoring files  if needed.
> Disable noUnusedLocals and noUnusedParameters in tsconfig

- .changeset/nine-keys-accept.md
- jest-preset.js
- src/cli/adapter/prettier.ts
- src/cli/test/reporters/prettier/index.ts
This misappropriates Jest's reporter functionality so we can plug in to test file execution and re-format files that have updated snapshots.
Alternative to #1220.
> RFC: Format snapshot changes ourselves

- .changeset/silly-swans-serve.md
- .changeset/wild-plums-join.md
- docs/deep-dives/arm64.md
- src/cli/configure/patchDockerfile.test.ts
- src/cli/configure/patchDockerfile.ts
- src/cli/format.ts
- template/express-rest-api/Dockerfile
- template/koa-rest-api/Dockerfile
The current image has these vulnerabilities flagged in ECR but the new `-debian11` image is free from them.
For whatever reason, this image isn't using the latest deps/libs? I haven't quite looked at why but the documentation now recommends `gcr.io/distroless/nodejs18-debian11` by default
https://github.com/GoogleContainerTools/distroless/blob/main/nodejs/README.md
> Update distroless nodejs image

- docs/deep-dives/github.md
This "repo suffix" for Github API tokens is no longer relevant for SEEK-specific builds.
This is a documentation-only change.
> Update the Github "deep dive" to remove references to repo suffix for tokens

- .changeset/tiny-chairs-deliver.md
- src/cli/configure/patchRenovateConfig.test.ts
- src/cli/configure/patchRenovateConfig.ts
Noticed this when I was running `skuba init`
Not urgent as it can be resolved with a `yarn format` after it's been initialised.
> Fix Patch Renovate Config for `skuba init`

- .changeset/calm-tips-wait.md
- scripts/test-template.sh
- template/koa-rest-api/src/app.test.ts
The below unit tests do not fail when endpoint returns 404
We either use `expect` function or throw when check fails  https://github.com/ladjs/supertest#expectfunctionres-
Modify unit test
Add usage message when argument is not received
> fix supertest app.test.ts example

- .changeset/old-berries-train.md
- src/utils/template.ts
This resolves an "Invalid function return type" error on `skuba init`.
> init: Fix `skuba.template.js` validation

- template/oss-npm-package/.github/workflows/release.yml
- template/oss-npm-package/.releaserc
- template/oss-npm-package/README.md
> RFC: Template default branch in oss-npm-package

- src/cli/configure/upgrade/patches/7.3.1/addEmptyExports.test.ts
- src/cli/configure/upgrade/patches/7.3.1/patchServerListener.test.ts
- src/cli/lint.int.test.ts
These are just internal tests, but they are harmless to tweak and this may make it more obvious that we are intentionally choosing `fs-extra`.
https://github.com/seek-oss/skuba/pull/1274#discussion_r1424901691
> Use `fs-extra` more consistently

- .changeset/five-kiwis-laugh.md
- docs/deep-dives/arm64.md
- src/cli/__snapshots__/format.int.test.ts.snap
- src/cli/configure/upgrade/patches/7.3.1/index.ts
- src/cli/configure/upgrade/patches/7.3.1/patchDockerfile.test.ts
- src/cli/configure/upgrade/patches/7.3.1/patchDockerfile.ts
- template/express-rest-api/Dockerfile
- template/koa-rest-api/Dockerfile
Resolves https://github.com/seek-oss/skuba/issues/1380
> Patch to debian12

- .changeset/lucky-gorillas-grab.md
- template/express-rest-api/gantry.apply.yml
- template/koa-rest-api/gantry.apply.yml
Seems easy enough and it worked across our production services 🤷.
Closes #1230
> Set `readOnlyRootFilesystem`

- .changeset/pretty-needles-hope.md
- template/lambda-sqs-worker-cdk/cdk.json
- template/lambda-sqs-worker-cdk/infra/__snapshots__/appStack.test.ts.snap
- template/lambda-sqs-worker-cdk/infra/appStack.ts
- template/lambda-sqs-worker/serverless.yml
> Set Max Concurrency

- .eslintrc.js
- src/cli/configure/upgrade/patches/7.3.1/patchServerListener.test.ts
> Lint for `fs` usage

- src/cli/configure/upgrade/index.test.ts
- src/cli/configure/upgrade/index.ts
Apparently `index.d.ts` is not a valid semver :D
```
skuba    │ Failed to run skuba lints.
skuba    │ TypeError: Invalid Version: index.d.ts
at new SemVer (/Users/rling/Code/github.com/seek-oss/skuba/node_modules/.pnpm/semver@7.5.4/node_modules/semver/classes/semver.js:38:13)
at compare (/Users/rling/Code/github.com/seek-oss/skuba/node_modules/.pnpm/semver@7.5.4/node_modules/semver/functions/compare.js:3:3)
at gte (/Users/rling/Code/github.com/seek-oss/skuba/node_modules/.pnpm/semver@7.5.4/node_modules/semver/functions/gte.js:2:30)
at /Users/rling/Code/github.com/seek-oss/skuba/lib/cli/configure/upgrade/index.js:46:38
at Array.filter (<anonymous>)
at getPatches (/Users/rling/Code/github.com/seek-oss/skuba/lib/cli/configure/upgrade/index.js:44:13)
at async upgradeSkuba …
```
> Enumerate patch directories only

- template/express-rest-api/.buildkite/pipeline.yml
- template/express-rest-api/Dockerfile.dev-deps
- template/greeter/.buildkite/pipeline.yml
- template/greeter/Dockerfile
- template/koa-rest-api/.buildkite/pipeline.yml
- template/koa-rest-api/Dockerfile.dev-deps
- template/lambda-sqs-worker-cdk/.buildkite/pipeline.yml
- template/lambda-sqs-worker-cdk/Dockerfile
- template/lambda-sqs-worker/.buildkite/pipeline.yml
- template/lambda-sqs-worker/Dockerfile
Looks like `pnpm fetch` reads the `.npmrc` for settings and outputs a `publicHoistPattern` in `node_modules/.modules.yaml`
As a result, when we go to run `pnpm install --offline` it fails silently and asks if we would like to destroy `node_modules`
This results in `skuba` not being properly hoisted.
> add .npmrc mounts

- .changeset/rare-eggs-tell.md
- template/lambda-sqs-worker-cdk/infra/__snapshots__/appStack.test.ts.snap
- template/lambda-sqs-worker-cdk/infra/appStack.test.ts
- template/lambda-sqs-worker-cdk/infra/appStack.ts
This was pissing me off. The logical ids depend on the code, lock files, etc (e.g. in master get the snapshot passing then change Hello World! to Hello World!! and it'll fail). 
Low value in asserting on specific hash of all the content, so use a stable identifier.
> Fix lambda CDK snapshot churn

- src/cli/node.ts
- src/skuba.ts
Forgot that skuba node could be used in CI for maintenance-y things
> Allow skuba node to run forever

- .changeset/rare-rats-teach.md
- package.json
- pnpm-lock.yaml
- src/utils/dir.ts
We're getting some peer dependency issues between fdir and picomatch, IMO best to just kill it as we only use it one spot for a narrow scope / fairly simple use case (but also, how is directory crawling not built in?)
> Remove fdir dependency

- .changeset/light-cherries-refuse.md
- src/api/github/issueComment.test.ts
- src/api/github/issueComment.ts
I noticed that this looked obtuse in source code as the meaning of `87109344` was only captured in skuba's docstring.
> GitHub.putIssueComment: Support `userId: 'seek-build-agency'`

- .changeset/light-cherries-refuse.md
- .changeset/polite-pants-share.md
- .changeset/rare-rats-teach.md
- .changeset/stupid-planes-fetch.md
- package.json
- pnpm-lock.yaml
- src/skuba.ts
This is one idea I had; the other is to remove the dependency entirely.
https://seekchat.slack.com/archives/C03UM9GBGET/p1710315456217509
> Remove `why-is-node-running`

- .changeset/hip-ears-punch.md
- .changeset/slow-moons-matter.md
- jest/transform.js
- package.json
https://github.com/seek-oss/skuba/actions/runs/8338828529
Co-authored-by: Michael Taranto <mtaranto@seek.com.au>
> Jest.mergePreset: Fix compatibility with `NodeNext`

- .changeset/fresh-wasps-greet.md
- package.json
- pnpm-lock.yaml
We cannot go to 23 as it requires node 20, unless we wanna do it now?
https://github.com/seek-oss/skuba/pull/1385
> Bump semantic release

- .changeset/hip-lemons-relax.md
- jest/transform.js
SEEK-Jobs/shared-web-assets#50
> Jest.mergePreset: Fudge `Bundler` module resolution

- .changeset/clean-candles-design.md
- package.json
- pnpm-lock.yaml
Forgot to bump this in the eslint-config-skuba upgrade
> Bump Eslint Version

- .changeset/tasty-schools-sort.md
- docs/cli/run.md
- package.json
- template/express-rest-api/package.json
- template/express-rest-api/src/config.ts
- template/express-rest-api/src/framework/logging.ts
- template/express-rest-api/src/framework/metrics.ts
- template/express-rest-api/src/listen.ts
- template/koa-rest-api/package.json
- template/koa-rest-api/src/config.ts
- template/lambda-sqs-worker-cdk/src/config.ts
- template/lambda-sqs-worker/src/config.ts
Follows on from seek-oss/datadog-custom-metrics#286.
> template: Make all configuration values explicit

- .changeset/long-dots-jump.md
- template/koa-rest-api/src/app.test.ts
These are super dodgy because they often go unloved as an API evolves and end up sending real outbound requests to upstreams when you run the test suite. Typically the upstreams don't respond with a 404 so the tests still pass, but it's gross.
> template/koa-rest-api: Remove `not.toBe(404)`s

- docs/deep-dives/pnpm.md
Turns out this is required. Oops. We removed it in another repo due to a different change
> Fix pnpm guide

- .gitignore
- packages/eslint-config-skuba/.gitignore
- packages/skuba-dive/.gitignore
- src/cli/configure/analysis/__snapshots__/project.test.ts.snap
- template/base/_.gitignore
[cdk.context.json](https://docs.aws.amazon.com/cdk/v2/guide/context.html) is usually created when running `cdk` commands locally like:
```sh
cdk deploy
```
This file doesn't need to be checked because it gets generated on demand anyway and isn't required for builds.
> Add cdk.context.json to the base gitignore

- CONTRIBUTING.md
- package.json
- scripts/test-template.sh
- scripts/update-template-snapshot.sh
Add a new `pnpm test:template:updateSnapshot` script
It leverages existing `update-template.sh` and adds a `-u` option to update snapshot. It will update existing snapshots when running tests in `tmp-${template}` dir and copy the snapshots to `skuba/template` dir
To make it easier to avoid #1646 because I missed it in #1644
I initially thought to make `pnpm test:template` `--updateSnapshot` by default but I am unsure of the existing approach. Assuming that snapshots in template are meant as safeguard for template user and not skuba developers, it might be easier to just have a `husky pre-commit` hook to `--updateSnapshot` by default when modifying templates.
> Add pnpm command to update snapshot

- .changeset/renovate-6eb125a.md
- integration/base/patch/Dockerfile
- package.json
- pnpm-lock.yaml
- template/express-rest-api/package.json
- template/greeter/package.json
- template/koa-rest-api/package.json
- template/lambda-sqs-worker-cdk/package.json
- template/lambda-sqs-worker/package.json
- template/oss-npm-package/_package.json
- template/private-npm-package/_package.json
Discussed internally that we'd prefer to keep the node 18 support over the limited benefits that semantic-release gives us. 
Coupling a node upgrade to the lint upgrades means that node 18 users might not get autofixes; running skuba would fail with a node version error (I think?)
> Revert "deps: semantic-release ^24.0.0"

- scripts/test-template.sh
- template/lambda-sqs-worker-cdk/infra/__snapshots__/appStack.test.ts.snap
There were a few shellcheck warnings in this file relating to POSIX compatibility, and branches started to fail with suspiciously related issues; something under the hood in the GitHub Actions runners must have changed. Easy fix is to use bash given we have it!
(Drive-by cleanups of an incorrect check for `pnpm build` failures + trailing whitespace + failing snapshots)
> Fix integration tests

- .changeset/strange-bats-doubt.md
- src/cli/lint/autofix.test.ts
- src/cli/lint/autofix.ts
Reverts https://github.com/seek-oss/skuba/pull/1226/
Unblocked by https://github.com/seek-oss/rynovate/pull/121
> Remove old autofix logic

- packages/eslint-config-skuba/index.js
I saw a few:
```
.mockImplementation(() => { return Promise.reject('bad')});
```
and similar implementation across a few repos. Don't think it's worth forcing them to change it to a throw
> Allow Promise reject in tests

- .changeset/pink-seas-stare.md
- docs/deep-dives/pnpm.md
- src/cli/__snapshots__/format.int.test.ts.snap
- src/cli/lint/internalLints/upgrade/patches/8.2.1/collapseDuplicateMergeKeys.ts
- src/cli/lint/internalLints/upgrade/patches/8.2.1/index.ts
- src/cli/lint/internalLints/upgrade/patches/8.2.1/moveNpmrcMounts.test.ts
- src/cli/lint/internalLints/upgrade/patches/8.2.1/moveNpmrcMounts.ts
- template/express-rest-api/.buildkite/pipeline.yml
- template/greeter/.buildkite/pipeline.yml
- template/koa-rest-api/.buildkite/pipeline.yml
- template/lambda-sqs-worker-cdk/.buildkite/pipeline.yml
- template/lambda-sqs-worker/.buildkite/pipeline.yml
Don't ask how I noticed the bug :)
> Fix .npmrc handling

- README.md
I feel like a global installation of skuba isn't required, as `pnpm` natively caches it for us now so I would like to instead update our advice to using the latest version of skuba to initialise new projects.
> Remove advice for global installation

- .github/renovate.json5
https://github.com/seek-oss/skuba/pull/1703
```
 ERROR  This project is configured to use v9.12.0 of pnpm. Your current pnpm is v9.12.1
If you want to bypass this version check, you can set the "package-manager-strict" configuration to "false" or set the "COREPACK_ENABLE_STRICT" environment variable to "0"
```
Not sure if this will make it available it in the repo level `pnpm` updates but we can always test it.
> Exclude pnpm from template- renovates

- .changeset/strange-cameras-brake.md
- docs/deep-dives/pnpm.md
- src/cli/__snapshots__/format.int.test.ts.snap
- src/cli/lint/internalLints/upgrade/patches/9.0.1/index.ts
- src/cli/lint/internalLints/upgrade/patches/9.0.1/patchPnpmDockerImages.test.ts
- src/cli/lint/internalLints/upgrade/patches/9.0.1/patchPnpmDockerImages.ts
- template/express-rest-api/Dockerfile.dev-deps
- template/greeter/Dockerfile
- template/koa-rest-api/Dockerfile.dev-deps
- template/lambda-sqs-worker-cdk/Dockerfile
- template/lambda-sqs-worker/Dockerfile
Corepack seems to always fetch the latest package manager if you don't have a `package.json` present despite us installing a specific version of `pnpm` beforehand. This autofixes our Dockerfiles to always mount the package.json file when running a pnpm command
https://seekchat.slack.com/archives/C07C02YUF9S/p1729154703475989?thread_ts=1729142626.867769&cid=C07C02YUF9S
> Patch Pnpm Dockerfile

- src/cli/lint/internalLints/upgrade/patches/9.0.1/patchPnpmDockerImages.test.ts
- src/cli/lint/internalLints/upgrade/patches/9.0.1/patchPnpmDockerImages.ts
This one irks me because vscode behaves differently around Dockerfiles? On this repo it seems to do spaces of 4 but on others I get 2.
https://github.com/seek-oss/skuba/blob/91af3b6a6d503f7c964e03e9cda48adad4e4c44e/template/lambda-sqs-worker/Dockerfile#L13-L17
This is indented by 4 and when I save it on vscode it doesn't format it.
But on this [repo](https://github.com/SEEK-Jobs/indie-graphql-server/blob/121ae87b1b04bec47195b44affed5ace1bff43b6/Dockerfile.dev-deps#L7-L8) there's a mix of 2 indent and 4 indent and when I save it makes it 2 indent.
So this PR decides to check how the other stuff is indented and copies the indentation.
Prettier does not care about Dockerfiles.
> Consider indentation in pnpm Dockerfile autofix

- .changeset/wet-owls-attack.md
- packages/eslint-config-skuba/index.js
We have more modern defaults specified in `eslint-config-seek/base`.
- https://github.com/seek-oss/eslint-config-seek/blob/b06e07d6370c5a0bd585a6dc30ffd7708ff68e06/base.js#L120-L121
- https://github.com/seek-oss/eslint-config-seek/blob/b06e07d6370c5a0bd585a6dc30ffd7708ff68e06/base.js#L138-L141
This may require some manual testing to ensure it doesn't break things on a typical back-end repository that still uses CommonJS.
> RFC: Try to remove ESLint `languageOptions`

- .changeset/hip-dolphins-explode.md
- template/lambda-sqs-worker-cdk/Dockerfile
https://seek.enterprise.slack.com/archives/C03UM9GBGET/p1737666444601339?thread_ts=1730694830.237809&cid=C03UM9GBGET
> Add git to Docker Image 

- .changeset/twenty-poets-bake.md
- docs/deep-dives/arm64.md
- template/express-rest-api/.buildkite/pipeline.yml
- template/koa-rest-api/.buildkite/pipeline.yml
Upgrade Gantry pipeline plugin to `v4.0.0`
> Upgrade Gantry pipeline plugin

- .changeset/yellow-paws-train.md
- src/cli/init/index.ts
Fixes `init` usage when used with `pnpm dlx`. At the moment it doesn't pass in the `destinationDir` so it fails to find the skuba manifest which we create in the line before.
Before:
After:
A little tricky to test with our integration tests/not worth my time
> Fix pnpm dlx usage

- .changeset/free-bats-jump.md
- package.json
- pnpm-lock.yaml
- src/cli/configure/analyseDependencies.ts
- src/cli/migrate/nodeVersion/getNodeTypesVersion.test.ts
- src/cli/migrate/nodeVersion/getNodeTypesVersion.ts
- src/utils/version.ts
`npm-registry-fetch` was used in the skuba migration code, and its purpose clashes with `libnpmsearch`, which is also causing us annoyance in https://github.com/seek-oss/skuba/pull/1758. 
While there, I was able to drop `validate-npm-package-name` (we'll just get a 404, which is probably fine?).
> Dedupe some deps

- .changeset/itchy-crabs-mate.md
- .changeset/nasty-masks-eat.md
- docs/cli/lint.md
- docs/cli/migrate.md
Sorry for 🐌 turnaround on this
> Tweak migration doco

- .changeset/chilled-onions-doubt.md
- docs/cli/migrate.md
- src/cli/configure/index.ts
- src/cli/format.int.test.ts
- src/cli/migrate/nodeVersion/checks.ts
- src/cli/migrate/nodeVersion/index.ts
- src/utils/packageManager.test.ts
- src/utils/packageManager.ts
- Determine Node package via presence of `files` field.
- Re-lock after the upgrade.
> Skuba Node Upgrade Fixes

- .changeset/breezy-donkeys-lick.md
- src/cli/migrate/nodeVersion/checks.test.ts
- src/cli/migrate/nodeVersion/checks.ts
- src/cli/migrate/nodeVersion/index.ts
At the moment, `isPatchableSkubaType` keeps checking the root directory's package.json file, where it should be checking for the nearest package.json to the file that we have.
Before:
After:
> Consider current path when finding parent package.json

- .changeset/three-wasps-prove.md
- packages/eslint-config-skuba/package.json
- pnpm-lock.yaml
This should make skuba upgrades be seamless, hopefully.
> Require latest eslint-config-seek 

- docs/deep-dives/pnpm.md
This has been missed a few times. I'm hoping that having the keyword in here serves as a sufficient reminder.
> Mention CODEOWNERS in pnpm migration doc

- .changeset/common-corners-fall.md
- jest/transform.js
- src/api/github/pullRequest.ts
Looks like when you do a lock file maintenance on the Octokit deps the type issues you see in other repos disappear as they properly added `type: 'module'` to their package jsons.
This one is the only thing that complains in my project.
```bash
node_modules/.pnpm/skuba@11.0.0_@babel+core@7.27.1_@jest+transform@29.7.0_@swc+core@1.11.29_@typescript-es_d151c735ea38d56f044e010092928178/node_modules/skuba/lib/api/github/pullRequest.d.ts(1,30): error TS1541: Type-only import of an ECMAScript module from a CommonJS module must have a 'resolution-mode' attribute.
```
> Fix Node16 module compatibility

- .changeset/fast-regions-arrive.md
- src/cli/migrate/nodeVersion/index.ts
In some repos with many files that need replacing and/or testing, the mutability of RegExp objects (TIL, thanks @kjots) was causing some changes to fail in the .test, or miss changes in the .replaceAll.
> JavaScript [RegExp](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp) objects are stateful when they have the [global](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/global) or [sticky](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/sticky) flags set (e.g., /foo/g or /foo/y). They store a [lastIndex](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/lastIndex) from the previous match. Using this internally, test() can be used to …
> Fix migrate node bug

- packages/eslint-config-skuba/requireExtensions.js
- packages/eslint-config-skuba/requireExtensions.test.ts
Was doing some testing and it looks like dynamic imports also need extensions. Once again will keep testing this through snapshots on a bunch of repos
> Add dynamic import handling to ESLint rule

- .changeset/clever-taxis-turn.md
- .changeset/sad-glasses-unite.md
Don't ask me why.
Tested with `pnpm changeset version`
> Apparently you gotta double $$

- .changeset/eighty-kids-prove.md
- packages/eslint-config-skuba/index.js
- packages/eslint-config-skuba/requireExtensions.js
- packages/eslint-config-skuba/requireExtensions.test.ts
- packages/eslint-config-skuba/src/index.ts
Unfortunately Jest's TypeScript processor doesn't use modern standards and can't read TypeScript files with `.js` extensions 🙄. So any `.js` extension it encounters will cause an error.
This change won't stop cases where someone may import another TypeScript file which is using extensions but should prevent a decent majority of cases.
See: https://github.com/SEEK-Jobs/indie-graphql-server/pull/3325/commits/40fdf8a5f150a98e9fe6edd1adf7b2692e18f6f7 as an example.
> Prevent Jest config and setup files from being linted

- .github/renovate.json5
Looks like we're falling behind here because we have a couple parked Renovates hogging our concurrent limit. I am hoping to work on those soon™️ but I anticipate this will recur at various points.
> Increase our own `prConcurrentLimit`

- template/lambda-sqs-worker-cdk/src/framework/handler.test.ts
Paragraph was sometimes creating paragraph's too large so it was getting truncated by our logger. See: https://github.com/seek-oss/skuba/actions/runs/16665133351/job/47169798967?pr=1976
Changed beforeEach to afterEach for consistency with the other files
> Fix flakey tests

- src/cli/lint/internalLints/upgrade/patches/12.0.2/unhandledRejections.test.ts
- src/cli/lint/internalLints/upgrade/patches/12.0.2/unhandledRejections.ts
NBD but https://github.com/search?q=org%3ASEEK-Jobs%20path%3A**%2Flogging%2Findex.ts&type=code
> Handle `/index` and `.ts` logging imports

- packages/eslint-plugin-skuba/src/rules/no-sync-in-promise-iterable.test.ts
- packages/eslint-plugin-skuba/src/rules/no-sync-in-promise-iterable.ts
> RFC: Allow `knex` builder in `Promise` method

- docs/deep-dives/esm.md
Setting [`rootDir` ](https://www.typescriptlang.org/tsconfig/#rootDir) to `.` means that the `src` folder ends up in our `lib` output.
So we need to also modify `tsconfig.build.json` to point to `src` so that it isn't included in the output
> Apply tweaks to the ESM plan

- .changeset/bright-buckets-tie.md
- pnpm-workspace.yaml
- template/base/_pnpm-workspace.yaml
Some tooling (*cough *cough Jest) relies on looking for TypeScript in the root folder. Otherwise it goes searching through your whole computer looking for node_modules/typescript. I imagine there's some other things that also require it so I don't see too much harm in hoisting it up.
> Hoist TypeScript

- .changeset/cool-pants-wonder.md
- docs/eslint-plugin/no-sync-in-promise-iterable.md
- packages/eslint-plugin-skuba/src/rules/no-sync-in-promise-iterable.test.ts
- packages/eslint-plugin-skuba/src/rules/no-sync-in-promise-iterable.ts
- src/cli/build/assets.ts
- src/cli/init/getConfig.ts
- src/cli/lint/internal.ts
- src/cli/lint/internalLints/upgrade/patches/8.2.1/upgradeESLint.ts
- src/wrapper/main.test.ts
This bites the bullet and starts tracking whether a given function will be invoked. This means we stop traversing `() => () => () => fail()` if we are confident it won't reach `fail()`, and allows us to properly model the relative safety of `.then()` and `Promise.try()` callbacks.
> lint: Plug `Promise.try()` and `Promise.resolve().then()`

- .changeset/fresh-ducks-clap.md
- template/lambda-sqs-worker-cdk/infra/__snapshots__/appStack.test.ts.snap
- template/lambda-sqs-worker-cdk/infra/appStack.ts
Given our telemetry instrumentation we should give this a little more juice by default
> Bump default memory to 512mb

- .changeset/many-moles-rescue.md
- .changeset/silly-poems-prove.md
- packages/eslint-plugin-skuba/src/rules/no-sync-in-promise-iterable.test.ts
- packages/eslint-plugin-skuba/src/rules/no-sync-in-promise-iterable.ts
This should make sure that the report is always against the relevant argument to the static `Promise` method. It tries to maintain some context of the underlying issue by printing the relevant expression and its `line:column` location.
https://seekchat.slack.com/archives/C06QWMV5BSA/p1755051180841209
> Line up `skuba/no-sync-in-promise-iterable` to Promise

- .github/workflows/release.yml
- .github/workflows/validate.yml
- template/oss-npm-package/.github/workflows/release.yml
- template/oss-npm-package/.github/workflows/validate.yml
I think we're stuck with this until `devEngines` support is ubiquitous.
https://redirect.github.com/actions/setup-node/issues/1255
> Use `.nvmrc` in GitHub workflows

- .changeset/fluffy-mangos-scream.md
- .changeset/tough-bobcats-post.md
- packages/eslint-plugin-skuba/src/rules/no-sync-in-promise-iterable.test.ts
- packages/eslint-plugin-skuba/src/rules/no-sync-in-promise-iterable.ts
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array#static_methods
> lint: Support static `Array` methods

- .changeset/hip-shrimps-fail.md
- packages/api/package.json
- packages/api/scripts/fix-types.sh
- packages/api/src/github/issueComment.ts
- packages/api/src/github/octokit.ts
- packages/eslint-plugin-skuba/package.json
- pnpm-lock.yaml
Should be temporary as we shift to ESM.
Octokit is technically ESM: https://arethetypeswrong.github.io/?p=%40octokit%2Frest%4022.0.0 so it causes us grief.
This dirty script changes:
to the valid syntax of:
> Commit Crimes
